-- ============================================================
-- canonical_menus 시드 데이터 (고속도로 휴게소 음식 기반)
-- 생성일: 2026-02-19 13:14
-- 소스: data.ex.co.kr 휴게소 음식 메뉴 API (7,009건)
-- 대상: 5곳 이상 휴게소에서 판매되는 보편적 메뉴 169개
-- ============================================================

-- 기존 시드 데이터 정리 (필요시)
-- DELETE FROM canonical_menus WHERE source = 'highway_food_data';

INSERT INTO canonical_menus (
    id, name_ko, translations, description, concept_id,
    tags, source, category_1, category_2, serving_size,
    nutrition_info, last_nutrition_updated,
    created_at, updated_at
) VALUES
  (gen_random_uuid(), '유부우동', '{"ko": "유부우동"}', '{"ko": "면류 > 면"}', NULL, '["면류", "면"]', 'highway_food_data', '면류', '면', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '꼬치어묵우동', '{"ko": "꼬치어묵우동"}', '{"ko": "면류 > 면"}', NULL, '["면류", "면"]', 'highway_food_data', '면류', '면', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '치즈돈가스', '{"ko": "치즈돈가스"}', '{"ko": "돈가스/튀김 > 돈가스"}', NULL, '["돈가스/튀김", "돈가스"]', 'highway_food_data', '돈가스/튀김', '돈가스', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '떡만두라면', '{"ko": "떡만두라면"}', '{"ko": "면류 > 라면"}', NULL, '["면류", "라면"]', 'highway_food_data', '면류', '라면', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '떡라면', '{"ko": "떡라면"}', '{"ko": "면류 > 라면"}', NULL, '["면류", "라면"]', 'highway_food_data', '면류', '라면', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '짜장면', '{"ko": "짜장면"}', '{"ko": "중식 > 중식"}', NULL, '["중식", "중식"]', 'highway_food_data', '중식', '중식', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '해물순두부찌개', '{"ko": "해물순두부찌개"}', '{"ko": "국/찌개/탕 > 찌개"}', NULL, '["국/찌개/탕", "찌개"]', 'highway_food_data', '국/찌개/탕', '찌개', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '우동', '{"ko": "우동"}', '{"ko": "면류 > 면"}', NULL, '["면류", "면"]', 'highway_food_data', '면류', '면', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '등심돈가스', '{"ko": "등심돈가스"}', '{"ko": "돈가스/튀김 > 돈가스"}', NULL, '["돈가스/튀김", "돈가스"]', 'highway_food_data', '돈가스/튀김', '돈가스', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '라면', '{"ko": "라면"}', '{"ko": "면류 > 라면"}', NULL, '["면류", "라면"]', 'highway_food_data', '면류', '라면', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '새우튀김우동', '{"ko": "새우튀김우동"}', '{"ko": "면류 > 면"}', NULL, '["면류", "면"]', 'highway_food_data', '면류', '면', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '육개장', '{"ko": "육개장"}', '{"ko": "국/찌개/탕 > 국"}', NULL, '["국/찌개/탕", "국"]', 'highway_food_data', '국/찌개/탕', '국', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '왕돈가스', '{"ko": "왕돈가스"}', '{"ko": "돈가스/튀김 > 돈가스"}', NULL, '["돈가스/튀김", "돈가스"]', 'highway_food_data', '돈가스/튀김', '돈가스', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '제육덮밥', '{"ko": "제육덮밥"}', '{"ko": "밥류 > 덮밥"}', NULL, '["밥류", "덮밥"]', 'highway_food_data', '밥류', '덮밥', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '된장찌개', '{"ko": "된장찌개"}', '{"ko": "국/찌개/탕 > 찌개"}', NULL, '["국/찌개/탕", "찌개"]', 'highway_food_data', '국/찌개/탕', '찌개', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '뚝배기불고기', '{"ko": "뚝배기불고기"}', '{"ko": "구이/고기 > 구이"}', NULL, '["구이/고기", "구이"]', 'highway_food_data', '구이/고기', '구이', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '돈가스', '{"ko": "돈가스"}', '{"ko": "돈가스/튀김 > 돈가스"}', NULL, '["돈가스/튀김", "돈가스"]', 'highway_food_data', '돈가스/튀김', '돈가스', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '순두부찌개', '{"ko": "순두부찌개"}', '{"ko": "국/찌개/탕 > 찌개"}', NULL, '["국/찌개/탕", "찌개"]', 'highway_food_data', '국/찌개/탕', '찌개', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '야채튀김우동', '{"ko": "야채튀김우동"}', '{"ko": "면류 > 면"}', NULL, '["면류", "면"]', 'highway_food_data', '면류', '면', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '치즈라면', '{"ko": "치즈라면"}', '{"ko": "면류 > 라면"}', NULL, '["면류", "라면"]', 'highway_food_data', '면류', '라면', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '김치찌개', '{"ko": "김치찌개"}', '{"ko": "국/찌개/탕 > 찌개"}', NULL, '["국/찌개/탕", "찌개"]', 'highway_food_data', '국/찌개/탕', '찌개', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '잔치국수', '{"ko": "잔치국수"}', '{"ko": "면류 > 면"}', NULL, '["면류", "면"]', 'highway_food_data', '면류', '면', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '돌솥비빔밥', '{"ko": "돌솥비빔밥"}', '{"ko": "밥류 > 비빔밥"}', NULL, '["밥류", "비빔밥"]', 'highway_food_data', '밥류', '비빔밥', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '차돌된장찌개', '{"ko": "차돌된장찌개"}', '{"ko": "국/찌개/탕 > 찌개"}', NULL, '["국/찌개/탕", "찌개"]', 'highway_food_data', '국/찌개/탕', '찌개', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '어묵우동', '{"ko": "어묵우동"}', '{"ko": "면류 > 면"}', NULL, '["면류", "면"]', 'highway_food_data', '면류', '면', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '소고기국밥', '{"ko": "소고기국밥"}', '{"ko": "밥류 > 기타밥"}', NULL, '["밥류", "기타밥"]', 'highway_food_data', '밥류', '기타밥', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '돼지고기김치찌개', '{"ko": "돼지고기김치찌개"}', '{"ko": "국/찌개/탕 > 찌개"}', NULL, '["국/찌개/탕", "찌개"]', 'highway_food_data', '국/찌개/탕', '찌개', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '남산왕돈까스', '{"ko": "남산왕돈까스"}', '{"ko": "돈가스/튀김 > 돈가스"}', NULL, '["돈가스/튀김", "돈가스"]', 'highway_food_data', '돈가스/튀김', '돈가스', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '충무김밥', '{"ko": "충무김밥"}', '{"ko": "밥류 > 김밥"}', NULL, '["밥류", "김밥"]', 'highway_food_data', '밥류', '김밥', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '왕새우튀김우동', '{"ko": "왕새우튀김우동"}', '{"ko": "면류 > 면"}', NULL, '["면류", "면"]', 'highway_food_data', '면류', '면', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '남산치즈돈까스', '{"ko": "남산치즈돈까스"}', '{"ko": "돈가스/튀김 > 돈가스"}', NULL, '["돈가스/튀김", "돈가스"]', 'highway_food_data', '돈가스/튀김', '돈가스', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '소떡소떡', '{"ko": "소떡소떡"}', '{"ko": "기타 > 기타"}', NULL, '["기타", "기타"]', 'highway_food_data', '기타', '기타', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '김치우동', '{"ko": "김치우동"}', '{"ko": "면류 > 면"}', NULL, '["면류", "면"]', 'highway_food_data', '면류', '면', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '콩나물해장라면', '{"ko": "콩나물해장라면"}', '{"ko": "면류 > 라면"}', NULL, '["면류", "라면"]', 'highway_food_data', '면류', '라면', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '냉모밀', '{"ko": "냉모밀"}', '{"ko": "기타 > 기타"}', NULL, '["기타", "기타"]', 'highway_food_data', '기타', '기타', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '돼지김치찌개', '{"ko": "돼지김치찌개"}', '{"ko": "국/찌개/탕 > 찌개"}', NULL, '["국/찌개/탕", "찌개"]', 'highway_food_data', '국/찌개/탕', '찌개', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '설렁탕', '{"ko": "설렁탕"}', '{"ko": "국/찌개/탕 > 탕"}', NULL, '["국/찌개/탕", "탕"]', 'highway_food_data', '국/찌개/탕', '탕', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '호두과자', '{"ko": "호두과자"}', '{"ko": "기타 > 기타"}', NULL, '["기타", "기타"]', 'highway_food_data', '기타', '기타', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '통감자', '{"ko": "통감자"}', '{"ko": "기타 > 기타"}', NULL, '["기타", "기타"]', 'highway_food_data', '기타', '기타', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '부산어묵우동', '{"ko": "부산어묵우동"}', '{"ko": "면류 > 면"}', NULL, '["면류", "면"]', 'highway_food_data', '면류', '면', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '황태해장국', '{"ko": "황태해장국"}', '{"ko": "국/찌개/탕 > 탕"}', NULL, '["국/찌개/탕", "탕"]', 'highway_food_data', '국/찌개/탕', '탕', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '떡볶이', '{"ko": "떡볶이"}', '{"ko": "분식 > 분식"}', NULL, '["분식", "분식"]', 'highway_food_data', '분식', '분식', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '장터국밥', '{"ko": "장터국밥"}', '{"ko": "밥류 > 기타밥"}', NULL, '["밥류", "기타밥"]', 'highway_food_data', '밥류', '기타밥', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '콩나물국밥', '{"ko": "콩나물국밥"}', '{"ko": "밥류 > 기타밥"}', NULL, '["밥류", "기타밥"]', 'highway_food_data', '밥류', '기타밥', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '바삭어포', '{"ko": "바삭어포"}', '{"ko": "기타 > 기타"}', NULL, '["기타", "기타"]', 'highway_food_data', '기타', '기타', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '라면정식', '{"ko": "라면정식"}', '{"ko": "면류 > 라면"}', NULL, '["면류", "라면"]', 'highway_food_data', '면류', '라면', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '남산매운돈까스', '{"ko": "남산매운돈까스"}', '{"ko": "돈가스/튀김 > 돈가스"}', NULL, '["돈가스/튀김", "돈가스"]', 'highway_food_data', '돈가스/튀김', '돈가스', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '강원나물밥', '{"ko": "강원나물밥"}', '{"ko": "밥류 > 기타밥"}', NULL, '["밥류", "기타밥"]', 'highway_food_data', '밥류', '기타밥', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '새우볶음밥', '{"ko": "새우볶음밥"}', '{"ko": "밥류 > 덮밥"}', NULL, '["밥류", "덮밥"]', 'highway_food_data', '밥류', '덮밥', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '소고기미역국', '{"ko": "소고기미역국"}', '{"ko": "국/찌개/탕 > 국"}', NULL, '["국/찌개/탕", "국"]', 'highway_food_data', '국/찌개/탕', '국', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '떡만두국', '{"ko": "떡만두국"}', '{"ko": "국/찌개/탕 > 국"}', NULL, '["국/찌개/탕", "국"]', 'highway_food_data', '국/찌개/탕', '국', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '떡만두라면정식', '{"ko": "떡만두라면정식"}', '{"ko": "면류 > 라면"}', NULL, '["면류", "라면"]', 'highway_food_data', '면류', '라면', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '옛날돈가스', '{"ko": "옛날돈가스"}', '{"ko": "돈가스/튀김 > 돈가스"}', NULL, '["돈가스/튀김", "돈가스"]', 'highway_food_data', '돈가스/튀김', '돈가스', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '옛날핫도그', '{"ko": "옛날핫도그"}', '{"ko": "분식 > 분식"}', NULL, '["분식", "분식"]', 'highway_food_data', '분식', '분식', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '우렁된장찌개', '{"ko": "우렁된장찌개"}', '{"ko": "국/찌개/탕 > 찌개"}', NULL, '["국/찌개/탕", "찌개"]', 'highway_food_data', '국/찌개/탕', '찌개', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '치킨팝콘', '{"ko": "치킨팝콘"}', '{"ko": "기타 > 기타"}', NULL, '["기타", "기타"]', 'highway_food_data', '기타', '기타', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '꼬치어묵', '{"ko": "꼬치어묵"}', '{"ko": "분식 > 분식"}', NULL, '["분식", "분식"]', 'highway_food_data', '분식', '분식', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '어묵라면', '{"ko": "어묵라면"}', '{"ko": "면류 > 라면"}', NULL, '["면류", "라면"]', 'highway_food_data', '면류', '라면', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '놀부부대찌개', '{"ko": "놀부부대찌개"}', '{"ko": "국/찌개/탕 > 찌개"}', NULL, '["국/찌개/탕", "찌개"]', 'highway_food_data', '국/찌개/탕', '찌개', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '소고기장터국밥', '{"ko": "소고기장터국밥"}', '{"ko": "밥류 > 기타밥"}', NULL, '["밥류", "기타밥"]', 'highway_food_data', '밥류', '기타밥', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '추어탕', '{"ko": "추어탕"}', '{"ko": "국/찌개/탕 > 탕"}', NULL, '["국/찌개/탕", "탕"]', 'highway_food_data', '국/찌개/탕', '탕', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '갈비탕', '{"ko": "갈비탕"}', '{"ko": "국/찌개/탕 > 탕"}', NULL, '["국/찌개/탕", "탕"]', 'highway_food_data', '국/찌개/탕', '탕', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '들깨미역국', '{"ko": "들깨미역국"}', '{"ko": "국/찌개/탕 > 국"}', NULL, '["국/찌개/탕", "국"]', 'highway_food_data', '국/찌개/탕', '국', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '핫도그', '{"ko": "핫도그"}', '{"ko": "분식 > 분식"}', NULL, '["분식", "분식"]', 'highway_food_data', '분식', '분식', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '얼큰순대국', '{"ko": "얼큰순대국"}', '{"ko": "국/찌개/탕 > 국"}', NULL, '["국/찌개/탕", "국"]', 'highway_food_data', '국/찌개/탕', '국', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '버섯된장찌개', '{"ko": "버섯된장찌개"}', '{"ko": "국/찌개/탕 > 찌개"}', NULL, '["국/찌개/탕", "찌개"]', 'highway_food_data', '국/찌개/탕', '찌개', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '물냉면', '{"ko": "물냉면"}', '{"ko": "면류 > 면"}', NULL, '["면류", "면"]', 'highway_food_data', '면류', '면', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '해물순두부', '{"ko": "해물순두부"}', '{"ko": "기타 > 기타"}', NULL, '["기타", "기타"]', 'highway_food_data', '기타', '기타', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '흑돼지김치찌개', '{"ko": "흑돼지김치찌개"}', '{"ko": "국/찌개/탕 > 찌개"}', NULL, '["국/찌개/탕", "찌개"]', 'highway_food_data', '국/찌개/탕', '찌개', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '해물바', '{"ko": "해물바"}', '{"ko": "기타 > 기타"}', NULL, '["기타", "기타"]', 'highway_food_data', '기타', '기타', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '매직핫도그', '{"ko": "매직핫도그"}', '{"ko": "분식 > 분식"}', NULL, '["분식", "분식"]', 'highway_food_data', '분식', '분식', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '통등심돈가스', '{"ko": "통등심돈가스"}', '{"ko": "돈가스/튀김 > 돈가스"}', NULL, '["돈가스/튀김", "돈가스"]', 'highway_food_data', '돈가스/튀김', '돈가스', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '콩나물해장국', '{"ko": "콩나물해장국"}', '{"ko": "국/찌개/탕 > 탕"}', NULL, '["국/찌개/탕", "탕"]', 'highway_food_data', '국/찌개/탕', '탕', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '옥수수', '{"ko": "옥수수"}', '{"ko": "기타 > 기타"}', NULL, '["기타", "기타"]', 'highway_food_data', '기타', '기타', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '오뎅꼬치우동', '{"ko": "오뎅꼬치우동"}', '{"ko": "면류 > 면"}', NULL, '["면류", "면"]', 'highway_food_data', '면류', '면', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '옛날돈까스', '{"ko": "옛날돈까스"}', '{"ko": "돈가스/튀김 > 돈가스"}', NULL, '["돈가스/튀김", "돈가스"]', 'highway_food_data', '돈가스/튀김', '돈가스', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '짬뽕밥', '{"ko": "짬뽕밥"}', '{"ko": "밥류 > 기타밥"}', NULL, '["밥류", "기타밥"]', 'highway_food_data', '밥류', '기타밥', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '돈가스우동정식', '{"ko": "돈가스우동정식"}', '{"ko": "면류 > 면"}', NULL, '["면류", "면"]', 'highway_food_data', '면류', '면', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '맑은나주곰탕', '{"ko": "맑은나주곰탕"}', '{"ko": "국/찌개/탕 > 탕"}', NULL, '["국/찌개/탕", "탕"]', 'highway_food_data', '국/찌개/탕', '탕', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '튀김우동', '{"ko": "튀김우동"}', '{"ko": "면류 > 면"}', NULL, '["면류", "면"]', 'highway_food_data', '면류', '면', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '산채비빔밥', '{"ko": "산채비빔밥"}', '{"ko": "밥류 > 비빔밥"}', NULL, '["밥류", "비빔밥"]', 'highway_food_data', '밥류', '비빔밥', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '냄비우동', '{"ko": "냄비우동"}', '{"ko": "면류 > 면"}', NULL, '["면류", "면"]', 'highway_food_data', '면류', '면', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '불고기비빔밥', '{"ko": "불고기비빔밥"}', '{"ko": "밥류 > 비빔밥"}', NULL, '["밥류", "비빔밥"]', 'highway_food_data', '밥류', '비빔밥', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '제육볶음', '{"ko": "제육볶음"}', '{"ko": "중식 > 중식"}', NULL, '["중식", "중식"]', 'highway_food_data', '중식', '중식', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '야채김밥', '{"ko": "야채김밥"}', '{"ko": "밥류 > 김밥"}', NULL, '["밥류", "김밥"]', 'highway_food_data', '밥류', '김밥', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '옛날우동', '{"ko": "옛날우동"}', '{"ko": "면류 > 면"}', NULL, '["면류", "면"]', 'highway_food_data', '면류', '면', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '순대국밥', '{"ko": "순대국밥"}', '{"ko": "밥류 > 기타밥"}', NULL, '["밥류", "기타밥"]', 'highway_food_data', '밥류', '기타밥', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '비빔냉면', '{"ko": "비빔냉면"}', '{"ko": "면류 > 면"}', NULL, '["면류", "면"]', 'highway_food_data', '면류', '면', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '새집추어탕', '{"ko": "새집추어탕"}', '{"ko": "국/찌개/탕 > 탕"}', NULL, '["국/찌개/탕", "탕"]', 'highway_food_data', '국/찌개/탕', '탕', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '한우소머리곰탕', '{"ko": "한우소머리곰탕"}', '{"ko": "국/찌개/탕 > 탕"}', NULL, '["국/찌개/탕", "탕"]', 'highway_food_data', '국/찌개/탕', '탕', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '회오리감자', '{"ko": "회오리감자"}', '{"ko": "기타 > 기타"}', NULL, '["기타", "기타"]', 'highway_food_data', '기타', '기타', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '만두라면', '{"ko": "만두라면"}', '{"ko": "면류 > 라면"}', NULL, '["면류", "라면"]', 'highway_food_data', '면류', '라면', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '해장라면', '{"ko": "해장라면"}', '{"ko": "면류 > 라면"}', NULL, '["면류", "라면"]', 'highway_food_data', '면류', '라면', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '바우네나주곰탕', '{"ko": "바우네나주곰탕"}', '{"ko": "국/찌개/탕 > 탕"}', NULL, '["국/찌개/탕", "탕"]', 'highway_food_data', '국/찌개/탕', '탕', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '고기만두', '{"ko": "고기만두"}', '{"ko": "빵/간식 > 간식"}', NULL, '["빵/간식", "간식"]', 'highway_food_data', '빵/간식', '간식', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '얼큰곰탕', '{"ko": "얼큰곰탕"}', '{"ko": "국/찌개/탕 > 탕"}', NULL, '["국/찌개/탕", "탕"]', 'highway_food_data', '국/찌개/탕', '탕', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '해물짬뽕라면', '{"ko": "해물짬뽕라면"}', '{"ko": "면류 > 라면"}', NULL, '["면류", "라면"]', 'highway_food_data', '면류', '라면', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '열무국수', '{"ko": "열무국수"}', '{"ko": "면류 > 면"}', NULL, '["면류", "면"]', 'highway_food_data', '면류', '면', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '짬뽕', '{"ko": "짬뽕"}', '{"ko": "중식 > 중식"}', NULL, '["중식", "중식"]', 'highway_food_data', '중식', '중식', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '함박스테이크', '{"ko": "함박스테이크"}', '{"ko": "기타 > 기타"}', NULL, '["기타", "기타"]', 'highway_food_data', '기타', '기타', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '해물된장찌개', '{"ko": "해물된장찌개"}', '{"ko": "국/찌개/탕 > 찌개"}', NULL, '["국/찌개/탕", "찌개"]', 'highway_food_data', '국/찌개/탕', '찌개', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '얼큰우동', '{"ko": "얼큰우동"}', '{"ko": "면류 > 면"}', NULL, '["면류", "면"]', 'highway_food_data', '면류', '면', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '대파육개장', '{"ko": "대파육개장"}', '{"ko": "국/찌개/탕 > 국"}', NULL, '["국/찌개/탕", "국"]', 'highway_food_data', '국/찌개/탕', '국', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '돼지고기 김치찌개', '{"ko": "돼지고기 김치찌개"}', '{"ko": "국/찌개/탕 > 찌개"}', NULL, '["국/찌개/탕", "찌개"]', 'highway_food_data', '국/찌개/탕', '찌개', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '신라면', '{"ko": "신라면"}', '{"ko": "면류 > 라면"}', NULL, '["면류", "라면"]', 'highway_food_data', '면류', '라면', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '순대국', '{"ko": "순대국"}', '{"ko": "국/찌개/탕 > 국"}', NULL, '["국/찌개/탕", "국"]', 'highway_food_data', '국/찌개/탕', '국', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '실속돈가스', '{"ko": "실속돈가스"}', '{"ko": "돈가스/튀김 > 돈가스"}', NULL, '["돈가스/튀김", "돈가스"]', 'highway_food_data', '돈가스/튀김', '돈가스', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '모듬튀김우동', '{"ko": "모듬튀김우동"}', '{"ko": "면류 > 면"}', NULL, '["면류", "면"]', 'highway_food_data', '면류', '면', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '한우국밥', '{"ko": "한우국밥"}', '{"ko": "밥류 > 기타밥"}', NULL, '["밥류", "기타밥"]', 'highway_food_data', '밥류', '기타밥', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '옛날돼지고기김치찌개', '{"ko": "옛날돼지고기김치찌개"}', '{"ko": "국/찌개/탕 > 찌개"}', NULL, '["국/찌개/탕", "찌개"]', 'highway_food_data', '국/찌개/탕', '찌개', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '매콤제육덮밥', '{"ko": "매콤제육덮밥"}', '{"ko": "밥류 > 덮밥"}', NULL, '["밥류", "덮밥"]', 'highway_food_data', '밥류', '덮밥', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '차돌박이된장찌개', '{"ko": "차돌박이된장찌개"}', '{"ko": "국/찌개/탕 > 찌개"}', NULL, '["국/찌개/탕", "찌개"]', 'highway_food_data', '국/찌개/탕', '찌개', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '흑돼지 김치찌개', '{"ko": "흑돼지 김치찌개"}', '{"ko": "국/찌개/탕 > 찌개"}', NULL, '["국/찌개/탕", "찌개"]', 'highway_food_data', '국/찌개/탕', '찌개', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '만두국', '{"ko": "만두국"}', '{"ko": "국/찌개/탕 > 국"}', NULL, '["국/찌개/탕", "국"]', 'highway_food_data', '국/찌개/탕', '국', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '황태미역국', '{"ko": "황태미역국"}', '{"ko": "국/찌개/탕 > 국"}', NULL, '["국/찌개/탕", "국"]', 'highway_food_data', '국/찌개/탕', '국', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '꼬지어묵우동', '{"ko": "꼬지어묵우동"}', '{"ko": "면류 > 면"}', NULL, '["면류", "면"]', 'highway_food_data', '면류', '면', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '참치김치찌개', '{"ko": "참치김치찌개"}', '{"ko": "국/찌개/탕 > 찌개"}', NULL, '["국/찌개/탕", "찌개"]', 'highway_food_data', '국/찌개/탕', '찌개', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '돈가스제육덮밥', '{"ko": "돈가스제육덮밥"}', '{"ko": "밥류 > 덮밥"}', NULL, '["밥류", "덮밥"]', 'highway_food_data', '밥류', '덮밥', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '몽글순두부찌개', '{"ko": "몽글순두부찌개"}', '{"ko": "국/찌개/탕 > 찌개"}', NULL, '["국/찌개/탕", "찌개"]', 'highway_food_data', '국/찌개/탕', '찌개', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '콩나물황태해장국', '{"ko": "콩나물황태해장국"}', '{"ko": "국/찌개/탕 > 탕"}', NULL, '["국/찌개/탕", "탕"]', 'highway_food_data', '국/찌개/탕', '탕', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '부대라면', '{"ko": "부대라면"}', '{"ko": "면류 > 라면"}', NULL, '["면류", "라면"]', 'highway_food_data', '면류', '라면', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '비빔밥', '{"ko": "비빔밥"}', '{"ko": "밥류 > 비빔밥"}', NULL, '["밥류", "비빔밥"]', 'highway_food_data', '밥류', '비빔밥', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '김치만두', '{"ko": "김치만두"}', '{"ko": "빵/간식 > 간식"}', NULL, '["빵/간식", "간식"]', 'highway_food_data', '빵/간식', '간식', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '해장라면정식', '{"ko": "해장라면정식"}', '{"ko": "면류 > 라면"}', NULL, '["면류", "라면"]', 'highway_food_data', '면류', '라면', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '선지해장국', '{"ko": "선지해장국"}', '{"ko": "국/찌개/탕 > 탕"}', NULL, '["국/찌개/탕", "탕"]', 'highway_food_data', '국/찌개/탕', '탕', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '치즈돈가스+사이다세트', '{"ko": "치즈돈가스+사이다세트"}', '{"ko": "돈가스/튀김 > 돈가스"}', NULL, '["돈가스/튀김", "돈가스"]', 'highway_food_data', '돈가스/튀김', '돈가스', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '남산돈까스', '{"ko": "남산돈까스"}', '{"ko": "돈가스/튀김 > 돈가스"}', NULL, '["돈가스/튀김", "돈가스"]', 'highway_food_data', '돈가스/튀김', '돈가스', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '당면짬뽕밥', '{"ko": "당면짬뽕밥"}', '{"ko": "밥류 > 기타밥"}', NULL, '["밥류", "기타밥"]', 'highway_food_data', '밥류', '기타밥', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '해물냄비우동', '{"ko": "해물냄비우동"}', '{"ko": "면류 > 면"}', NULL, '["면류", "면"]', 'highway_food_data', '면류', '면', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '케이크소세지', '{"ko": "케이크소세지"}', '{"ko": "기타 > 기타"}', NULL, '["기타", "기타"]', 'highway_food_data', '기타', '기타', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '케네디소시지', '{"ko": "케네디소시지"}', '{"ko": "기타 > 기타"}', NULL, '["기타", "기타"]', 'highway_food_data', '기타', '기타', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '꼬치어묵라면', '{"ko": "꼬치어묵라면"}', '{"ko": "면류 > 라면"}', NULL, '["면류", "라면"]', 'highway_food_data', '면류', '라면', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '농심유부우동', '{"ko": "농심유부우동"}', '{"ko": "면류 > 면"}', NULL, '["면류", "면"]', 'highway_food_data', '면류', '면', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '바지락미역국', '{"ko": "바지락미역국"}', '{"ko": "국/찌개/탕 > 국"}', NULL, '["국/찌개/탕", "국"]', 'highway_food_data', '국/찌개/탕', '국', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '김치볶음밥', '{"ko": "김치볶음밥"}', '{"ko": "밥류 > 덮밥"}', NULL, '["밥류", "덮밥"]', 'highway_food_data', '밥류', '덮밥', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '가락자장면', '{"ko": "가락자장면"}', '{"ko": "기타 > 기타"}', NULL, '["기타", "기타"]', 'highway_food_data', '기타', '기타', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '사골우거지국밥', '{"ko": "사골우거지국밥"}', '{"ko": "밥류 > 기타밥"}', NULL, '["밥류", "기타밥"]', 'highway_food_data', '밥류', '기타밥', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '고추장불고기', '{"ko": "고추장불고기"}', '{"ko": "구이/고기 > 구이"}', NULL, '["구이/고기", "구이"]', 'highway_food_data', '구이/고기', '구이', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '계란떡라면', '{"ko": "계란떡라면"}', '{"ko": "면류 > 라면"}', NULL, '["면류", "라면"]', 'highway_food_data', '면류', '라면', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '사골우거지국', '{"ko": "사골우거지국"}', '{"ko": "국/찌개/탕 > 국"}', NULL, '["국/찌개/탕", "국"]', 'highway_food_data', '국/찌개/탕', '국', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '수제어묵바', '{"ko": "수제어묵바"}', '{"ko": "분식 > 분식"}', NULL, '["분식", "분식"]', 'highway_food_data', '분식', '분식', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '명동칼국수', '{"ko": "명동칼국수"}', '{"ko": "면류 > 면"}', NULL, '["면류", "면"]', 'highway_food_data', '면류', '면', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '순두부짬뽕밥', '{"ko": "순두부짬뽕밥"}', '{"ko": "밥류 > 기타밥"}', NULL, '["밥류", "기타밥"]', 'highway_food_data', '밥류', '기타밥', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '델리만쥬', '{"ko": "델리만쥬"}', '{"ko": "기타 > 기타"}', NULL, '["기타", "기타"]', 'highway_food_data', '기타', '기타', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '고등어구이', '{"ko": "고등어구이"}', '{"ko": "구이/고기 > 구이"}', NULL, '["구이/고기", "구이"]', 'highway_food_data', '구이/고기', '구이', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '돈육김치찌개', '{"ko": "돈육김치찌개"}', '{"ko": "국/찌개/탕 > 찌개"}', NULL, '["국/찌개/탕", "찌개"]', 'highway_food_data', '국/찌개/탕', '찌개', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '얼큰육개장', '{"ko": "얼큰육개장"}', '{"ko": "국/찌개/탕 > 국"}', NULL, '["국/찌개/탕", "국"]', 'highway_food_data', '국/찌개/탕', '국', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '미니츄러스', '{"ko": "미니츄러스"}', '{"ko": "기타 > 기타"}', NULL, '["기타", "기타"]', 'highway_food_data', '기타', '기타', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '도깨비핫도그', '{"ko": "도깨비핫도그"}', '{"ko": "분식 > 분식"}', NULL, '["분식", "분식"]', 'highway_food_data', '분식', '분식', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '사골떡만두국', '{"ko": "사골떡만두국"}', '{"ko": "국/찌개/탕 > 국"}', NULL, '["국/찌개/탕", "국"]', 'highway_food_data', '국/찌개/탕', '국', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '고등어구이정식', '{"ko": "고등어구이정식"}', '{"ko": "밥류 > 기타밥"}', NULL, '["밥류", "기타밥"]', 'highway_food_data', '밥류', '기타밥', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '군만두', '{"ko": "군만두"}', '{"ko": "빵/간식 > 간식"}', NULL, '["빵/간식", "간식"]', 'highway_food_data', '빵/간식', '간식', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '콩국수', '{"ko": "콩국수"}', '{"ko": "면류 > 면"}', NULL, '["면류", "면"]', 'highway_food_data', '면류', '면', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '어린이돈가스', '{"ko": "어린이돈가스"}', '{"ko": "돈가스/튀김 > 돈가스"}', NULL, '["돈가스/튀김", "돈가스"]', 'highway_food_data', '돈가스/튀김', '돈가스', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '제육돈가스', '{"ko": "제육돈가스"}', '{"ko": "돈가스/튀김 > 돈가스"}', NULL, '["돈가스/튀김", "돈가스"]', 'highway_food_data', '돈가스/튀김', '돈가스', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '짬뽕순두부', '{"ko": "짬뽕순두부"}', '{"ko": "중식 > 중식"}', NULL, '["중식", "중식"]', 'highway_food_data', '중식', '중식', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '곰탕', '{"ko": "곰탕"}', '{"ko": "국/찌개/탕 > 탕"}', NULL, '["국/찌개/탕", "탕"]', 'highway_food_data', '국/찌개/탕', '탕', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '전주비빔밥', '{"ko": "전주비빔밥"}', '{"ko": "밥류 > 비빔밥"}', NULL, '["밥류", "비빔밥"]', 'highway_food_data', '밥류', '비빔밥', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '이해윤추어탕', '{"ko": "이해윤추어탕"}', '{"ko": "국/찌개/탕 > 탕"}', NULL, '["국/찌개/탕", "탕"]', 'highway_food_data', '국/찌개/탕', '탕', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '냉메밀', '{"ko": "냉메밀"}', '{"ko": "기타 > 기타"}', NULL, '["기타", "기타"]', 'highway_food_data', '기타', '기타', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '전복꼬치어묵우동', '{"ko": "전복꼬치어묵우동"}', '{"ko": "면류 > 면"}', NULL, '["면류", "면"]', 'highway_food_data', '면류', '면', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '파김치', '{"ko": "파김치"}', '{"ko": "기타 > 기타"}', NULL, '["기타", "기타"]', 'highway_food_data', '기타', '기타', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '햄치즈라면', '{"ko": "햄치즈라면"}', '{"ko": "면류 > 라면"}', NULL, '["면류", "라면"]', 'highway_food_data', '면류', '라면', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '샘밭막국수', '{"ko": "샘밭막국수"}', '{"ko": "면류 > 면"}', NULL, '["면류", "면"]', 'highway_food_data', '면류', '면', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '경양식돈가스', '{"ko": "경양식돈가스"}', '{"ko": "돈가스/튀김 > 돈가스"}', NULL, '["돈가스/튀김", "돈가스"]', 'highway_food_data', '돈가스/튀김', '돈가스', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '짬뽕라면', '{"ko": "짬뽕라면"}', '{"ko": "면류 > 라면"}', NULL, '["면류", "라면"]', 'highway_food_data', '면류', '라면', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '그냥라면', '{"ko": "그냥라면"}', '{"ko": "면류 > 라면"}', NULL, '["면류", "라면"]', 'highway_food_data', '면류', '라면', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '남산치즈돈가스', '{"ko": "남산치즈돈가스"}', '{"ko": "돈가스/튀김 > 돈가스"}', NULL, '["돈가스/튀김", "돈가스"]', 'highway_food_data', '돈가스/튀김', '돈가스', NULL, '{}', NULL, NOW(), NOW()),
  (gen_random_uuid(), '야채비빔밥', '{"ko": "야채비빔밥"}', '{"ko": "밥류 > 비빔밥"}', NULL, '["밥류", "비빔밥"]', 'highway_food_data', '밥류', '비빔밥', NULL, '{}', NULL, NOW(), NOW());

-- 인덱스 확인
-- CREATE INDEX IF NOT EXISTS idx_cm_category ON canonical_menus(category_1, category_2);
-- CREATE INDEX IF NOT EXISTS idx_cm_name_ko ON canonical_menus(name_ko);
