-- ============================================================================
-- Sprint 2 Phase 1: Multi-Image and Enriched Content Schema Extension
-- ============================================================================
-- Purpose: Add support for multiple images and detailed content fields
-- Target Table: canonical_menus
-- Date: 2026-02-19
-- Author: backend-dev
--
-- Changes:
--   1. Migrate image_url (TEXT) → primary_image (JSONB)
--   2. Add images[] array for additional images
--   3. Add long-form descriptions (Korean + English)
--   4. Add enriched content fields (regional variants, preparation, nutrition, etc.)
--   5. Add content_completeness score
--
-- Safety: All new columns are NULLABLE to prevent breaking existing data
-- Rollback: See rollback_sprint2_phase1.sql
-- ============================================================================

BEGIN;

-- ============================================================================
-- PART 1: Add New Columns
-- ============================================================================

-- Image fields
ALTER TABLE canonical_menus
  ADD COLUMN IF NOT EXISTS primary_image JSONB DEFAULT NULL;

COMMENT ON COLUMN canonical_menus.primary_image IS
  'Primary image with metadata: {url: string, source: string, license: string, attribution: string}';

ALTER TABLE canonical_menus
  ADD COLUMN IF NOT EXISTS images JSONB[] DEFAULT NULL;

COMMENT ON COLUMN canonical_menus.images IS
  'Array of additional images with same structure as primary_image';

-- Long-form descriptions
ALTER TABLE canonical_menus
  ADD COLUMN IF NOT EXISTS description_long_ko TEXT DEFAULT NULL;

COMMENT ON COLUMN canonical_menus.description_long_ko IS
  'Detailed Korean description (3-5 paragraphs) for in-depth understanding';

ALTER TABLE canonical_menus
  ADD COLUMN IF NOT EXISTS description_long_en TEXT DEFAULT NULL;

COMMENT ON COLUMN canonical_menus.description_long_en IS
  'Detailed English description (3-5 paragraphs) generated by GPT-4o';

-- Enriched content fields
ALTER TABLE canonical_menus
  ADD COLUMN IF NOT EXISTS regional_variants JSONB DEFAULT NULL;

COMMENT ON COLUMN canonical_menus.regional_variants IS
  'Regional variations: {region: string, differences: string, local_name: string}[]';

ALTER TABLE canonical_menus
  ADD COLUMN IF NOT EXISTS preparation_steps JSONB DEFAULT NULL;

COMMENT ON COLUMN canonical_menus.preparation_steps IS
  'How to eat/prepare: {steps: string[], serving_suggestions: string[], etiquette: string[]}';

ALTER TABLE canonical_menus
  ADD COLUMN IF NOT EXISTS nutrition_detail JSONB DEFAULT NULL;

COMMENT ON COLUMN canonical_menus.nutrition_detail IS
  'Nutritional information: {calories: int, protein: float, carbs: float, fat: float, sodium: int}';

ALTER TABLE canonical_menus
  ADD COLUMN IF NOT EXISTS flavor_profile JSONB DEFAULT NULL;

COMMENT ON COLUMN canonical_menus.flavor_profile IS
  'Taste characteristics: {primary: string[], balance: {sweet: int, salty: int, sour: int, bitter: int, umami: int}}';

ALTER TABLE canonical_menus
  ADD COLUMN IF NOT EXISTS visitor_tips JSONB DEFAULT NULL;

COMMENT ON COLUMN canonical_menus.visitor_tips IS
  'Tips for foreign visitors: {common_mistakes: string[], ordering_tips: string[], pairing: string[]}';

ALTER TABLE canonical_menus
  ADD COLUMN IF NOT EXISTS similar_dishes JSONB[] DEFAULT NULL;

COMMENT ON COLUMN canonical_menus.similar_dishes IS
  'Similar dishes: {name_ko: string, name_en: string, similarity_reason: string, difference: string}[]';

-- Content completeness score
ALTER TABLE canonical_menus
  ADD COLUMN IF NOT EXISTS content_completeness DECIMAL(5,2) DEFAULT 0.00 CHECK (content_completeness >= 0 AND content_completeness <= 100);

COMMENT ON COLUMN canonical_menus.content_completeness IS
  'Content completeness percentage (0-100) based on filled fields';

-- ============================================================================
-- PART 2: Migrate Existing Data (image_url → primary_image)
-- ============================================================================

-- Convert existing image_url (TEXT) to primary_image (JSONB)
-- Only migrate non-null, non-empty image_url values
UPDATE canonical_menus
SET primary_image = jsonb_build_object(
  'url', image_url,
  'source', 'legacy_migration',
  'license', 'unknown',
  'attribution', NULL
)
WHERE image_url IS NOT NULL
  AND image_url != ''
  AND primary_image IS NULL;

-- ============================================================================
-- PART 3: Create Indexes for Performance
-- ============================================================================

-- GIN indexes for JSONB fields (required for fast queries)
CREATE INDEX IF NOT EXISTS idx_cm_primary_image_gin
  ON canonical_menus USING GIN (primary_image);

CREATE INDEX IF NOT EXISTS idx_cm_images_gin
  ON canonical_menus USING GIN (images);

CREATE INDEX IF NOT EXISTS idx_cm_regional_variants_gin
  ON canonical_menus USING GIN (regional_variants);

-- B-tree index for content_completeness (sorting/filtering)
CREATE INDEX IF NOT EXISTS idx_cm_content_completeness
  ON canonical_menus (content_completeness DESC NULLS LAST);

-- Partial index for highly complete content (≥90%)
CREATE INDEX IF NOT EXISTS idx_cm_content_complete
  ON canonical_menus (content_completeness)
  WHERE content_completeness >= 90.0;

-- ============================================================================
-- PART 4: Content Completeness Calculation Function and Trigger
-- ============================================================================

-- Function to calculate content completeness percentage (0-100)
CREATE OR REPLACE FUNCTION calculate_content_completeness(menu_row canonical_menus)
RETURNS DECIMAL(5,2) AS $$
DECLARE
    total_fields INT := 10;  -- Excluding content_completeness itself
    filled_fields INT := 0;
BEGIN
    -- Count filled enriched content fields
    IF menu_row.primary_image IS NOT NULL THEN
        filled_fields := filled_fields + 1;
    END IF;

    IF menu_row.images IS NOT NULL AND array_length(menu_row.images, 1) > 0 THEN
        filled_fields := filled_fields + 1;
    END IF;

    IF menu_row.description_long_ko IS NOT NULL AND LENGTH(menu_row.description_long_ko) > 0 THEN
        filled_fields := filled_fields + 1;
    END IF;

    IF menu_row.description_long_en IS NOT NULL AND LENGTH(menu_row.description_long_en) > 0 THEN
        filled_fields := filled_fields + 1;
    END IF;

    IF menu_row.regional_variants IS NOT NULL THEN
        filled_fields := filled_fields + 1;
    END IF;

    IF menu_row.preparation_steps IS NOT NULL THEN
        filled_fields := filled_fields + 1;
    END IF;

    IF menu_row.nutrition_detail IS NOT NULL THEN
        filled_fields := filled_fields + 1;
    END IF;

    IF menu_row.flavor_profile IS NOT NULL THEN
        filled_fields := filled_fields + 1;
    END IF;

    IF menu_row.visitor_tips IS NOT NULL THEN
        filled_fields := filled_fields + 1;
    END IF;

    IF menu_row.similar_dishes IS NOT NULL AND array_length(menu_row.similar_dishes, 1) > 0 THEN
        filled_fields := filled_fields + 1;
    END IF;

    -- Calculate percentage
    RETURN ROUND((filled_fields::DECIMAL / total_fields::DECIMAL) * 100, 2);
END;
$$ LANGUAGE plpgsql IMMUTABLE;

COMMENT ON FUNCTION calculate_content_completeness IS
  'Calculates content completeness percentage based on filled enriched content fields';

-- Trigger function to auto-update content_completeness on INSERT/UPDATE
CREATE OR REPLACE FUNCTION update_content_completeness()
RETURNS TRIGGER AS $$
BEGIN
    NEW.content_completeness := calculate_content_completeness(NEW);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger for automatic completeness calculation
DROP TRIGGER IF EXISTS trg_update_completeness ON canonical_menus;
CREATE TRIGGER trg_update_completeness
    BEFORE INSERT OR UPDATE ON canonical_menus
    FOR EACH ROW
    EXECUTE FUNCTION update_content_completeness();

COMMENT ON TRIGGER trg_update_completeness ON canonical_menus IS
  'Automatically updates content_completeness field on every insert/update';

-- ============================================================================
-- PART 5: Verification Queries
-- ============================================================================

DO $$
DECLARE
  migrated_count INT;
  total_count INT;
BEGIN
  -- Count migrated images
  SELECT COUNT(*) INTO migrated_count
  FROM canonical_menus
  WHERE primary_image IS NOT NULL;

  -- Count total menus
  SELECT COUNT(*) INTO total_count
  FROM canonical_menus;

  RAISE NOTICE 'Migration Complete:';
  RAISE NOTICE '  - Total menus: %', total_count;
  RAISE NOTICE '  - Migrated images: %', migrated_count;
  RAISE NOTICE '  - New columns added: 11';
  RAISE NOTICE '  - New indexes added: 3';
END $$;

COMMIT;

-- ============================================================================
-- Post-Migration Verification (Run manually)
-- ============================================================================

-- Verify new columns exist
SELECT
  column_name,
  data_type,
  is_nullable,
  column_default
FROM information_schema.columns
WHERE table_name = 'canonical_menus'
  AND column_name IN (
    'primary_image', 'images', 'description_long_ko', 'description_long_en',
    'regional_variants', 'preparation_steps', 'nutrition_detail',
    'flavor_profile', 'visitor_tips', 'similar_dishes', 'content_completeness'
  )
ORDER BY ordinal_position;

-- Verify indexes
SELECT
  indexname,
  indexdef
FROM pg_indexes
WHERE tablename = 'canonical_menus'
  AND indexname LIKE '%primary_image%'
   OR indexname LIKE '%images%'
   OR indexname LIKE '%content_completeness%';

-- Sample migrated data
SELECT
  id,
  name_ko,
  image_url AS old_image_url,
  primary_image->>'url' AS new_image_url,
  primary_image->>'source' AS source
FROM canonical_menus
WHERE primary_image IS NOT NULL
LIMIT 5;
