"""
Canonical Menu 확장 시드 데이터 (177개)
Sprint 3A: Knowledge Graph 강화 - 123개 → 300개+
카테고리별 추가 메뉴
"""

from typing import List, Dict, Any


def get_canonical_menu_extension() -> List[Dict[str, Any]]:
    """Canonical Menu 확장 시드 데이터 반환 (177개)"""

    menus = []

    # ========================================
    # 고기류 (Meat Dishes) - 30개
    # ========================================

    # 양념갈비, 차돌박이, 항정살, 갈매기살, 막창, 곱창, 족발, 보쌈 등
    menus.extend(
        [
            {
                "name_ko": "양념갈비",
                "name_en": "Yangnyeom Galbi (Marinated Beef Ribs)",
                "concept": "고기구이",
                "description_ko": "간장 양념에 재운 소갈비 구이",
                "description_en": "Grilled beef short ribs marinated in soy-based sweet sauce",
                "primary_ingredients": ["beef ribs", "soy sauce", "garlic", "sugar"],
                "allergens": ["beef", "soy"],
                "spice_level": 0,
                "difficulty_score": 2,
            },
            {
                "name_ko": "차돌박이",
                "name_en": "Chadolbagi (Beef Brisket)",
                "concept": "고기구이",
                "description_ko": "소 양지머리의 기름진 부위를 구워 먹는 고기",
                "description_en": "Thinly sliced beef brisket, grilled",
                "primary_ingredients": ["beef brisket"],
                "allergens": ["beef"],
                "spice_level": 0,
                "difficulty_score": 1,
            },
            {
                "name_ko": "갈매기살",
                "name_en": "Galmaegisal (Pork Skirt Meat)",
                "concept": "고기구이",
                "description_ko": "돼지 횡격막 부위의 고기를 구워 먹는 요리",
                "description_en": "Grilled pork skirt meat (diaphragm)",
                "primary_ingredients": ["pork skirt"],
                "allergens": ["pork"],
                "spice_level": 0,
                "difficulty_score": 1,
            },
            {
                "name_ko": "보쌈",
                "name_en": "Bossam (Boiled Pork Wraps)",
                "concept": "고기볶음",
                "description_ko": "삶은 돼지고기를 야채에 싸 먹는 요리",
                "description_en": "Boiled pork belly wrapped in leafy vegetables",
                "primary_ingredients": [
                    "pork belly",
                    "napa cabbage",
                    "garlic",
                    "salted shrimp",
                ],
                "allergens": ["pork", "shellfish"],
                "spice_level": 0,
                "difficulty_score": 2,
            },
            {
                "name_ko": "안창살",
                "name_en": "Anchangsal (Beef Inside Skirt)",
                "concept": "고기구이",
                "description_ko": "소 횡격막 안쪽 살을 구워 먹는 고기",
                "description_en": "Grilled beef inside skirt meat",
                "primary_ingredients": ["beef skirt"],
                "allergens": ["beef"],
                "spice_level": 0,
                "difficulty_score": 1,
            },
            {
                "name_ko": "토시살",
                "name_en": "Tosisal (Pork Shoulder)",
                "concept": "고기구이",
                "description_ko": "돼지 앞다리 부위를 구워 먹는 고기",
                "description_en": "Grilled pork shoulder meat",
                "primary_ingredients": ["pork shoulder"],
                "allergens": ["pork"],
                "spice_level": 0,
                "difficulty_score": 1,
            },
            {
                "name_ko": "우삼겹",
                "name_en": "Usamgyeop (Beef Belly)",
                "concept": "고기구이",
                "description_ko": "소 삼겹살을 구워 먹는 고기",
                "description_en": "Grilled beef belly, similar to pork belly",
                "primary_ingredients": ["beef belly"],
                "allergens": ["beef"],
                "spice_level": 0,
                "difficulty_score": 1,
            },
            {
                "name_ko": "소곱창",
                "name_en": "So Gopchang (Beef Small Intestines)",
                "concept": "육류안주",
                "description_ko": "소 곱창을 구워 먹는 요리",
                "description_en": "Grilled beef small intestines",
                "primary_ingredients": ["beef intestines"],
                "allergens": ["beef"],
                "spice_level": 1,
                "difficulty_score": 3,
            },
            {
                "name_ko": "대창",
                "name_en": "Daechang (Beef Large Intestines)",
                "concept": "육류안주",
                "description_ko": "소 대장을 구워 먹는 요리",
                "description_en": "Grilled beef large intestines",
                "primary_ingredients": ["beef large intestines"],
                "allergens": ["beef"],
                "spice_level": 1,
                "difficulty_score": 3,
            },
            {
                "name_ko": "염통",
                "name_en": "Yeomtong (Beef Heart)",
                "concept": "육류안주",
                "description_ko": "소 심장을 구워 먹는 요리",
                "description_en": "Grilled beef heart",
                "primary_ingredients": ["beef heart"],
                "allergens": ["beef"],
                "spice_level": 0,
                "difficulty_score": 2,
            },
            {
                "name_ko": "천엽",
                "name_en": "Cheonyeop (Beef Omasum)",
                "concept": "육류안주",
                "description_ko": "소의 제3위(천엽)를 데쳐 먹는 요리",
                "description_en": "Blanched beef omasum",
                "primary_ingredients": ["beef omasum"],
                "allergens": ["beef"],
                "spice_level": 0,
                "difficulty_score": 3,
            },
            {
                "name_ko": "양",
                "name_en": "Yang (Beef Tripe)",
                "concept": "육류안주",
                "description_ko": "소의 제1위(양)를 구워 먹는 요리",
                "description_en": "Grilled beef tripe",
                "primary_ingredients": ["beef tripe"],
                "allergens": ["beef"],
                "spice_level": 0,
                "difficulty_score": 3,
            },
            {
                "name_ko": "닭갈비",
                "name_en": "Dakgalbi (Spicy Stir-fried Chicken)",
                "concept": "고기볶음",
                "description_ko": "닭고기를 고추장 양념에 볶은 춘천 향토 음식",
                "description_en": "Spicy stir-fried chicken with vegetables, Chuncheon specialty",
                "primary_ingredients": [
                    "chicken",
                    "gochujang",
                    "cabbage",
                    "sweet potato",
                ],
                "allergens": ["chicken", "soy"],
                "spice_level": 3,
                "difficulty_score": 2,
            },
            {
                "name_ko": "통닭",
                "name_en": "Tongdak (Whole Fried Chicken)",
                "concept": "고기볶음",
                "description_ko": "통째로 튀긴 닭",
                "description_en": "Whole fried chicken",
                "primary_ingredients": ["chicken", "flour", "oil"],
                "allergens": ["chicken", "wheat"],
                "spice_level": 0,
                "difficulty_score": 2,
            },
            {
                "name_ko": "훈제오리",
                "name_en": "Hunjeoori (Smoked Duck)",
                "concept": "고기구이",
                "description_ko": "오리를 훈제하여 구워 먹는 요리",
                "description_en": "Smoked and grilled duck",
                "primary_ingredients": ["duck", "smoke"],
                "allergens": ["duck"],
                "spice_level": 0,
                "difficulty_score": 2,
            },
            {
                "name_ko": "오리구이",
                "name_en": "Origui (Grilled Duck)",
                "concept": "고기구이",
                "description_ko": "오리고기를 구워 먹는 요리",
                "description_en": "Grilled duck meat",
                "primary_ingredients": ["duck"],
                "allergens": ["duck"],
                "spice_level": 0,
                "difficulty_score": 2,
            },
            {
                "name_ko": "삼겹살구이",
                "name_en": "Samgyeopsal Gui (Grilled Pork Belly)",
                "concept": "고기구이",
                "description_ko": "삼겹살을 구워 먹는 요리",
                "description_en": "Grilled pork belly, Korea's favorite BBQ",
                "primary_ingredients": ["pork belly"],
                "allergens": ["pork"],
                "spice_level": 0,
                "difficulty_score": 1,
            },
            {
                "name_ko": "한우등심",
                "name_en": "Hanwoo Deungsim (Korean Beef Sirloin)",
                "concept": "고기구이",
                "description_ko": "한우 등심을 구워 먹는 고급 고기",
                "description_en": "Grilled Korean beef sirloin, premium quality",
                "primary_ingredients": ["Korean beef sirloin"],
                "allergens": ["beef"],
                "spice_level": 0,
                "difficulty_score": 1,
            },
            {
                "name_ko": "한우안심",
                "name_en": "Hanwoo Ansim (Korean Beef Tenderloin)",
                "concept": "고기구이",
                "description_ko": "한우 안심을 구워 먹는 최고급 고기",
                "description_en": "Grilled Korean beef tenderloin, most tender cut",
                "primary_ingredients": ["Korean beef tenderloin"],
                "allergens": ["beef"],
                "spice_level": 0,
                "difficulty_score": 1,
            },
            {
                "name_ko": "소등심",
                "name_en": "So Deungsim (Beef Sirloin)",
                "concept": "고기구이",
                "description_ko": "소 등심을 구워 먹는 고기",
                "description_en": "Grilled beef sirloin",
                "primary_ingredients": ["beef sirloin"],
                "allergens": ["beef"],
                "spice_level": 0,
                "difficulty_score": 1,
            },
            {
                "name_ko": "소안심",
                "name_en": "So Ansim (Beef Tenderloin)",
                "concept": "고기구이",
                "description_ko": "소 안심을 구워 먹는 고기",
                "description_en": "Grilled beef tenderloin",
                "primary_ingredients": ["beef tenderloin"],
                "allergens": ["beef"],
                "spice_level": 0,
                "difficulty_score": 1,
            },
            {
                "name_ko": "채끝살",
                "name_en": "Chaekkeut (Beef Striploin)",
                "concept": "고기구이",
                "description_ko": "소 등심의 끝 부분을 구워 먹는 고기",
                "description_en": "Grilled beef striploin",
                "primary_ingredients": ["beef striploin"],
                "allergens": ["beef"],
                "spice_level": 0,
                "difficulty_score": 1,
            },
            {
                "name_ko": "부채살",
                "name_en": "Buchaes (Beef Top Blade)",
                "concept": "고기구이",
                "description_ko": "소 어깨 부위의 고기를 구워 먹는 요리",
                "description_en": "Grilled beef top blade, fan-shaped cut",
                "primary_ingredients": ["beef top blade"],
                "allergens": ["beef"],
                "spice_level": 0,
                "difficulty_score": 1,
            },
            {
                "name_ko": "살치살",
                "name_en": "Salchisal (Beef Outside Skirt)",
                "concept": "고기구이",
                "description_ko": "소 횡격막 바깥쪽 살을 구워 먹는 고기",
                "description_en": "Grilled beef outside skirt meat",
                "primary_ingredients": ["beef outside skirt"],
                "allergens": ["beef"],
                "spice_level": 0,
                "difficulty_score": 1,
            },
            {
                "name_ko": "우설",
                "name_en": "Useol (Beef Tongue)",
                "concept": "고기구이",
                "description_ko": "소 혀를 구워 먹는 요리",
                "description_en": "Grilled beef tongue",
                "primary_ingredients": ["beef tongue"],
                "allergens": ["beef"],
                "spice_level": 0,
                "difficulty_score": 2,
            },
            {
                "name_ko": "육전",
                "name_en": "Yukjeon (Pan-fried Beef)",
                "concept": "전",
                "description_ko": "소고기에 계란옷을 입혀 부친 전",
                "description_en": "Beef slices coated with egg and pan-fried",
                "primary_ingredients": ["beef", "egg", "flour"],
                "allergens": ["beef", "egg", "wheat"],
                "spice_level": 0,
                "difficulty_score": 2,
            },
            {
                "name_ko": "우족",
                "name_en": "Ujok (Beef Leg)",
                "concept": "찜",
                "description_ko": "소 족발을 푹 삶아 먹는 요리",
                "description_en": "Braised beef shank",
                "primary_ingredients": ["beef shank"],
                "allergens": ["beef"],
                "spice_level": 0,
                "difficulty_score": 3,
            },
            {
                "name_ko": "수육",
                "name_en": "Suyuk (Boiled Pork Slices)",
                "concept": "고기볶음",
                "description_ko": "돼지고기를 삶아 썰어 먹는 요리",
                "description_en": "Boiled pork slices, served cold",
                "primary_ingredients": ["pork", "garlic", "ginger"],
                "allergens": ["pork"],
                "spice_level": 0,
                "difficulty_score": 1,
            },
            {
                "name_ko": "닭발",
                "name_en": "Dakbal (Spicy Chicken Feet)",
                "concept": "고기볶음",
                "description_ko": "닭발을 매콤하게 볶은 요리",
                "description_en": "Spicy stir-fried chicken feet",
                "primary_ingredients": ["chicken feet", "gochujang"],
                "allergens": ["chicken", "soy"],
                "spice_level": 4,
                "difficulty_score": 3,
            },
            {
                "name_ko": "닭도리탕",
                "name_en": "Dakdoritang (Spicy Chicken Stew)",
                "concept": "찜",
                "description_ko": "닭을 감자와 함께 매콤하게 끓인 요리",
                "description_en": "Spicy chicken stew with potatoes",
                "primary_ingredients": ["chicken", "potato", "gochugaru", "soy sauce"],
                "allergens": ["chicken", "soy"],
                "spice_level": 3,
                "difficulty_score": 2,
            },
        ]
    )

    # ========================================
    # 해산물 (Seafood) - 20개
    # ========================================

    menus.extend(
        [
            {
                "name_ko": "꽃게찜",
                "name_en": "Kkotgetjjim (Steamed Blue Crab)",
                "concept": "찜",
                "description_ko": "꽃게를 쪄서 먹는 요리",
                "description_en": "Steamed blue crab",
                "primary_ingredients": ["blue crab"],
                "allergens": ["shellfish"],
                "spice_level": 0,
                "difficulty_score": 2,
            },
            {
                "name_ko": "간장게장",
                "name_en": "Ganjang Gejang (Soy Sauce Marinated Crab)",
                "concept": "젓갈",
                "description_ko": "생 게를 간장 양념에 재운 요리",
                "description_en": "Raw crab marinated in soy sauce",
                "primary_ingredients": ["raw crab", "soy sauce", "garlic"],
                "allergens": ["shellfish", "soy"],
                "spice_level": 0,
                "difficulty_score": 3,
            },
            {
                "name_ko": "양념게장",
                "name_en": "Yangnyeom Gejang (Spicy Marinated Crab)",
                "concept": "젓갈",
                "description_ko": "생 게를 고추장 양념에 재운 요리",
                "description_en": "Raw crab marinated in spicy sauce",
                "primary_ingredients": ["raw crab", "gochujang", "garlic"],
                "allergens": ["shellfish", "soy"],
                "spice_level": 3,
                "difficulty_score": 3,
            },
            {
                "name_ko": "물회",
                "name_en": "Mulhoe (Cold Raw Fish Soup)",
                "concept": "회",
                "description_ko": "회를 차가운 육수에 말아 먹는 여름 요리",
                "description_en": "Raw fish in cold spicy broth, summer dish",
                "primary_ingredients": [
                    "raw fish",
                    "vegetables",
                    "gochujang",
                    "vinegar",
                ],
                "allergens": ["fish", "soy"],
                "spice_level": 2,
                "difficulty_score": 2,
            },
            {
                "name_ko": "연어회",
                "name_en": "Yeoneo Hoe (Salmon Sashimi)",
                "concept": "회",
                "description_ko": "신선한 연어를 썰어 먹는 회",
                "description_en": "Fresh salmon slices, sashimi-style",
                "primary_ingredients": ["raw salmon"],
                "allergens": ["fish"],
                "spice_level": 0,
                "difficulty_score": 2,
            },
            {
                "name_ko": "광어회",
                "name_en": "Gwangeo Hoe (Flounder Sashimi)",
                "concept": "회",
                "description_ko": "신선한 광어를 썰어 먹는 회",
                "description_en": "Fresh flounder slices, sashimi-style",
                "primary_ingredients": ["raw flounder"],
                "allergens": ["fish"],
                "spice_level": 0,
                "difficulty_score": 2,
            },
            {
                "name_ko": "우럭회",
                "name_en": "Ureok Hoe (Rockfish Sashimi)",
                "concept": "회",
                "description_ko": "신선한 우럭을 썰어 먹는 회",
                "description_en": "Fresh rockfish slices, sashimi-style",
                "primary_ingredients": ["raw rockfish"],
                "allergens": ["fish"],
                "spice_level": 0,
                "difficulty_score": 2,
            },
            {
                "name_ko": "새우구이",
                "name_en": "Saeu Gui (Grilled Shrimp)",
                "concept": "생선구이",
                "description_ko": "새우를 구워 먹는 요리",
                "description_en": "Grilled shrimp",
                "primary_ingredients": ["shrimp"],
                "allergens": ["shellfish"],
                "spice_level": 0,
                "difficulty_score": 1,
            },
            {
                "name_ko": "전복구이",
                "name_en": "Jeonbok Gui (Grilled Abalone)",
                "concept": "생선구이",
                "description_ko": "전복을 구워 먹는 고급 요리",
                "description_en": "Grilled abalone, luxury seafood",
                "primary_ingredients": ["abalone", "butter"],
                "allergens": ["shellfish", "dairy"],
                "spice_level": 0,
                "difficulty_score": 2,
            },
            {
                "name_ko": "굴구이",
                "name_en": "Gul Gui (Grilled Oysters)",
                "concept": "생선구이",
                "description_ko": "굴을 구워 먹는 요리",
                "description_en": "Grilled oysters",
                "primary_ingredients": ["oysters"],
                "allergens": ["shellfish"],
                "spice_level": 0,
                "difficulty_score": 1,
            },
            {
                "name_ko": "낙지탕",
                "name_en": "Nakji Tang (Octopus Soup)",
                "concept": "탕",
                "description_ko": "낙지를 넣고 얼큰하게 끓인 국물 요리",
                "description_en": "Spicy octopus soup",
                "primary_ingredients": ["octopus", "vegetables", "gochugaru"],
                "allergens": ["seafood"],
                "spice_level": 3,
                "difficulty_score": 2,
            },
            {
                "name_ko": "주꾸미볶음",
                "name_en": "Jjukkumi Bokkeum (Spicy Webfoot Octopus)",
                "concept": "해물볶음",
                "description_ko": "주꾸미를 매콤하게 볶은 요리",
                "description_en": "Spicy stir-fried webfoot octopus",
                "primary_ingredients": ["webfoot octopus", "gochujang", "vegetables"],
                "allergens": ["seafood", "soy"],
                "spice_level": 4,
                "difficulty_score": 3,
            },
            {
                "name_ko": "산낙지",
                "name_en": "Sannakji (Live Octopus)",
                "concept": "회",
                "description_ko": "산 낙지를 썰어 먹는 요리",
                "description_en": "Live octopus, cut into pieces",
                "primary_ingredients": ["live octopus", "sesame oil"],
                "allergens": ["seafood", "sesame"],
                "spice_level": 0,
                "difficulty_score": 4,
            },
            {
                "name_ko": "문어숙회",
                "name_en": "Muneo Sukhoe (Blanched Octopus)",
                "concept": "회",
                "description_ko": "삶은 문어를 썰어 먹는 요리",
                "description_en": "Blanched octopus slices",
                "primary_ingredients": ["octopus"],
                "allergens": ["seafood"],
                "spice_level": 0,
                "difficulty_score": 2,
            },
            {
                "name_ko": "조개구이",
                "name_en": "Jogae Gui (Grilled Clams)",
                "concept": "생선구이",
                "description_ko": "조개를 구워 먹는 요리",
                "description_en": "Grilled clams",
                "primary_ingredients": ["clams"],
                "allergens": ["shellfish"],
                "spice_level": 0,
                "difficulty_score": 1,
            },
            {
                "name_ko": "매운탕",
                "name_en": "Maeuntang (Spicy Fish Stew)",
                "concept": "탕",
                "description_ko": "생선을 넣고 매콤하게 끓인 국물 요리",
                "description_en": "Spicy fish stew with vegetables",
                "primary_ingredients": ["fish", "vegetables", "gochugaru"],
                "allergens": ["fish"],
                "spice_level": 3,
                "difficulty_score": 2,
            },
            {
                "name_ko": "대구탕",
                "name_en": "Daegu Tang (Codfish Soup)",
                "concept": "탕",
                "description_ko": "대구를 넣고 맑게 끓인 국물 요리",
                "description_en": "Clear codfish soup",
                "primary_ingredients": ["codfish", "radish", "tofu"],
                "allergens": ["fish", "soy"],
                "spice_level": 1,
                "difficulty_score": 2,
            },
            {
                "name_ko": "복어탕",
                "name_en": "Bogeo Tang (Pufferfish Soup)",
                "concept": "탕",
                "description_ko": "복어를 넣고 끓인 고급 국물 요리",
                "description_en": "Pufferfish soup, luxury dish",
                "primary_ingredients": ["pufferfish", "vegetables"],
                "allergens": ["fish"],
                "spice_level": 1,
                "difficulty_score": 3,
            },
            {
                "name_ko": "조개탕",
                "name_en": "Jogae Tang (Clam Soup)",
                "concept": "탕",
                "description_ko": "조개를 넣고 시원하게 끓인 국물 요리",
                "description_en": "Refreshing clam soup",
                "primary_ingredients": ["clams", "tofu", "vegetables"],
                "allergens": ["shellfish", "soy"],
                "spice_level": 1,
                "difficulty_score": 1,
            },
            {
                "name_ko": "동태찌개",
                "name_en": "Dongtae Jjigae (Frozen Pollack Stew)",
                "concept": "찌개",
                "description_ko": "동태를 넣고 얼큰하게 끓인 찌개",
                "description_en": "Spicy stew with frozen pollack",
                "primary_ingredients": ["frozen pollack", "vegetables", "gochugaru"],
                "allergens": ["fish"],
                "spice_level": 2,
                "difficulty_score": 2,
            },
        ]
    )

    # ========================================
    # 국물요리 추가 (Soups & Stews) - 15개
    # ========================================

    menus.extend(
        [
            {
                "name_ko": "내장탕",
                "name_en": "Naejang Tang (Offal Soup)",
                "concept": "탕",
                "description_ko": "소 내장을 넣고 끓인 국물 요리",
                "description_en": "Soup with beef offal",
                "primary_ingredients": ["beef offal", "vegetables"],
                "allergens": ["beef"],
                "spice_level": 1,
                "difficulty_score": 3,
            },
            {
                "name_ko": "추어탕",
                "name_en": "Chueotang (Loach Soup)",
                "concept": "탕",
                "description_ko": "미꾸라지를 갈아 넣고 끓인 보양식",
                "description_en": "Ground loach soup, nutritious dish",
                "primary_ingredients": ["loach", "vegetables", "perilla"],
                "allergens": ["fish"],
                "spice_level": 1,
                "difficulty_score": 3,
            },
            {
                "name_ko": "우거지탕",
                "name_en": "Ugeoji Tang (Dried Cabbage Soup)",
                "concept": "탕",
                "description_ko": "우거지를 넣고 얼큰하게 끓인 국물 요리",
                "description_en": "Spicy soup with dried napa cabbage",
                "primary_ingredients": ["dried cabbage", "pork bones", "bean paste"],
                "allergens": ["pork", "soy"],
                "spice_level": 2,
                "difficulty_score": 2,
            },
            {
                "name_ko": "알탕",
                "name_en": "Altang (Fish Roe Soup)",
                "concept": "탕",
                "description_ko": "생선알을 넣고 매콤하게 끓인 국물 요리",
                "description_en": "Spicy soup with fish roe",
                "primary_ingredients": ["fish roe", "vegetables", "gochugaru"],
                "allergens": ["fish"],
                "spice_level": 3,
                "difficulty_score": 2,
            },
            {
                "name_ko": "닭곰탕",
                "name_en": "Dak Gomtang (Chicken Bone Soup)",
                "concept": "탕",
                "description_ko": "닭을 푹 끓여 진하게 만든 국물 요리",
                "description_en": "Rich chicken bone soup",
                "primary_ingredients": ["chicken", "ginseng", "garlic"],
                "allergens": ["chicken"],
                "spice_level": 0,
                "difficulty_score": 2,
            },
            {
                "name_ko": "도가니탕",
                "name_en": "Dogani Tang (Ox Knee Soup)",
                "concept": "탕",
                "description_ko": "소 무릎뼈를 오래 끓여 만든 국물 요리",
                "description_en": "Ox knee bone soup, rich in collagen",
                "primary_ingredients": ["ox knee bones", "beef"],
                "allergens": ["beef"],
                "spice_level": 0,
                "difficulty_score": 2,
            },
            {
                "name_ko": "꼬리곰탕",
                "name_en": "Kkori Gomtang (Oxtail Soup)",
                "concept": "탕",
                "description_ko": "소꼬리를 푹 끓여 만든 진한 국물 요리",
                "description_en": "Rich oxtail soup",
                "primary_ingredients": ["oxtail", "radish"],
                "allergens": ["beef"],
                "spice_level": 0,
                "difficulty_score": 2,
            },
            {
                "name_ko": "명태해장국",
                "name_en": "Myeongtae Haejangguk (Pollack Hangover Soup)",
                "concept": "해장국",
                "description_ko": "명태를 넣고 시원하게 끓인 해장국",
                "description_en": "Refreshing pollack hangover soup",
                "primary_ingredients": ["pollack", "bean sprouts", "tofu"],
                "allergens": ["fish", "soy"],
                "spice_level": 1,
                "difficulty_score": 2,
            },
            {
                "name_ko": "황태해장국",
                "name_en": "Hwangtae Haejangguk (Dried Pollack Hangover Soup)",
                "concept": "해장국",
                "description_ko": "황태를 넣고 시원하게 끓인 해장국",
                "description_en": "Dried pollack hangover soup",
                "primary_ingredients": ["dried pollack", "bean sprouts", "vegetables"],
                "allergens": ["fish"],
                "spice_level": 1,
                "difficulty_score": 2,
            },
            {
                "name_ko": "소머리국밥",
                "name_en": "Someori Gukbap (Ox Head Soup with Rice)",
                "concept": "국밥",
                "description_ko": "소머리를 푹 끓여 만든 국에 밥을 말아 먹는 요리",
                "description_en": "Ox head soup served with rice",
                "primary_ingredients": ["ox head", "rice"],
                "allergens": ["beef"],
                "spice_level": 0,
                "difficulty_score": 3,
            },
            {
                "name_ko": "콩국",
                "name_en": "Kongguk (Cold Soybean Soup)",
                "concept": "국",
                "description_ko": "콩을 갈아 차게 먹는 여름 국",
                "description_en": "Cold ground soybean soup, summer dish",
                "primary_ingredients": ["soybeans", "cucumber"],
                "allergens": ["soy"],
                "spice_level": 0,
                "difficulty_score": 2,
            },
            {
                "name_ko": "시래기국",
                "name_en": "Siraegi Guk (Dried Radish Greens Soup)",
                "concept": "국",
                "description_ko": "시래기를 넣고 구수하게 끓인 국",
                "description_en": "Soup with dried radish greens",
                "primary_ingredients": ["dried radish greens", "soybean paste"],
                "allergens": ["soy"],
                "spice_level": 0,
                "difficulty_score": 1,
            },
            {
                "name_ko": "무국",
                "name_en": "Mu Guk (Radish Soup)",
                "concept": "국",
                "description_ko": "무를 넣고 시원하게 끓인 국",
                "description_en": "Refreshing radish soup",
                "primary_ingredients": ["radish", "beef", "anchovy broth"],
                "allergens": ["beef", "fish"],
                "spice_level": 0,
                "difficulty_score": 1,
            },
            {
                "name_ko": "떡국",
                "name_en": "Tteokguk (Rice Cake Soup)",
                "concept": "국",
                "description_ko": "떡을 넣고 끓인 설날 음식",
                "description_en": "Rice cake soup, traditional New Year's dish",
                "primary_ingredients": ["rice cakes", "beef broth", "egg"],
                "allergens": ["beef", "egg"],
                "spice_level": 0,
                "difficulty_score": 1,
            },
            {
                "name_ko": "만둣국",
                "name_en": "Manduguk (Dumpling Soup)",
                "concept": "국",
                "description_ko": "만두를 넣고 끓인 국",
                "description_en": "Soup with dumplings",
                "primary_ingredients": ["dumplings", "beef broth"],
                "allergens": ["wheat", "pork", "beef"],
                "spice_level": 0,
                "difficulty_score": 1,
            },
        ]
    )

    # ========================================
    # 밥류 추가 (Rice Dishes) - 15개
    # ========================================

    menus.extend(
        [
            {
                "name_ko": "알밥",
                "name_en": "Albap (Fish Roe Rice Bowl)",
                "concept": "덮밥",
                "description_ko": "생선알을 밥 위에 얹은 덮밥",
                "description_en": "Rice bowl topped with fish roe",
                "primary_ingredients": ["rice", "fish roe", "seaweed", "sesame oil"],
                "allergens": ["fish", "sesame"],
                "spice_level": 0,
                "difficulty_score": 1,
            },
            {
                "name_ko": "낙지덮밥",
                "name_en": "Nakji Deopbap (Octopus Rice Bowl)",
                "concept": "덮밥",
                "description_ko": "매콤한 낙지볶음을 밥 위에 얹은 덮밥",
                "description_en": "Rice bowl with spicy stir-fried octopus",
                "primary_ingredients": ["rice", "octopus", "gochujang", "vegetables"],
                "allergens": ["seafood", "soy"],
                "spice_level": 3,
                "difficulty_score": 2,
            },
            {
                "name_ko": "오징어덮밥",
                "name_en": "Ojingeo Deopbap (Squid Rice Bowl)",
                "concept": "덮밥",
                "description_ko": "매콤한 오징어볶음을 밥 위에 얹은 덮밥",
                "description_en": "Rice bowl with spicy stir-fried squid",
                "primary_ingredients": ["rice", "squid", "gochujang", "vegetables"],
                "allergens": ["seafood", "soy"],
                "spice_level": 3,
                "difficulty_score": 2,
            },
            {
                "name_ko": "호박죽",
                "name_en": "Hobak Juk (Pumpkin Porridge)",
                "concept": "죽",
                "description_ko": "호박을 넣고 끓인 죽",
                "description_en": "Sweet pumpkin porridge",
                "primary_ingredients": ["pumpkin", "rice", "sugar"],
                "allergens": [],
                "spice_level": 0,
                "difficulty_score": 1,
            },
            {
                "name_ko": "잣죽",
                "name_en": "Jat Juk (Pine Nut Porridge)",
                "concept": "죽",
                "description_ko": "잣을 갈아 넣고 끓인 고급 죽",
                "description_en": "Porridge with ground pine nuts, luxury dish",
                "primary_ingredients": ["pine nuts", "rice"],
                "allergens": ["tree nuts"],
                "spice_level": 0,
                "difficulty_score": 2,
            },
            {
                "name_ko": "흑임자죽",
                "name_en": "Heugimja Juk (Black Sesame Porridge)",
                "concept": "죽",
                "description_ko": "검은깨를 갈아 넣고 끓인 죽",
                "description_en": "Porridge with ground black sesame",
                "primary_ingredients": ["black sesame", "rice"],
                "allergens": ["sesame"],
                "spice_level": 0,
                "difficulty_score": 1,
            },
            {
                "name_ko": "야채죽",
                "name_en": "Yachae Juk (Vegetable Porridge)",
                "concept": "죽",
                "description_ko": "각종 야채를 넣고 끓인 죽",
                "description_en": "Porridge with assorted vegetables",
                "primary_ingredients": ["rice", "vegetables", "sesame oil"],
                "allergens": ["sesame"],
                "spice_level": 0,
                "difficulty_score": 1,
            },
            {
                "name_ko": "솥밥",
                "name_en": "Sotbap (Stone Pot Rice)",
                "concept": "밥류",
                "description_ko": "돌솥에 지은 밥",
                "description_en": "Rice cooked in stone pot",
                "primary_ingredients": ["rice", "various toppings"],
                "allergens": [],
                "spice_level": 0,
                "difficulty_score": 2,
            },
            {
                "name_ko": "영양솥밥",
                "name_en": "Yeongyang Sotbap (Nutritious Stone Pot Rice)",
                "concept": "밥류",
                "description_ko": "영양가 있는 재료를 넣고 돌솥에 지은 밥",
                "description_en": "Nutritious rice cooked in stone pot with various ingredients",
                "primary_ingredients": ["rice", "chestnuts", "jujube", "ginseng"],
                "allergens": ["tree nuts"],
                "spice_level": 0,
                "difficulty_score": 2,
            },
            {
                "name_ko": "쌈밥",
                "name_en": "Ssambap (Leaf-wrapped Rice)",
                "concept": "밥류",
                "description_ko": "밥을 쌈 채소에 싸 먹는 요리",
                "description_en": "Rice wrapped in leafy vegetables",
                "primary_ingredients": [
                    "rice",
                    "lettuce",
                    "perilla leaves",
                    "ssamjang",
                ],
                "allergens": ["soy"],
                "spice_level": 0,
                "difficulty_score": 1,
            },
            {
                "name_ko": "볶음밥",
                "name_en": "Bokkeumbap (Fried Rice)",
                "concept": "볶음밥",
                "description_ko": "밥을 볶아 만든 요리",
                "description_en": "Korean-style fried rice",
                "primary_ingredients": ["rice", "vegetables", "egg"],
                "allergens": ["egg"],
                "spice_level": 0,
                "difficulty_score": 1,
            },
            {
                "name_ko": "카레라이스",
                "name_en": "Curry Rice",
                "concept": "덮밥",
                "description_ko": "카레를 밥 위에 얹은 요리",
                "description_en": "Rice with curry sauce",
                "primary_ingredients": ["rice", "curry", "vegetables", "meat"],
                "allergens": ["wheat"],
                "spice_level": 1,
                "difficulty_score": 1,
            },
            {
                "name_ko": "주먹밥",
                "name_en": "Jumeokbap (Rice Balls)",
                "concept": "밥류",
                "description_ko": "밥을 주먹으로 뭉쳐 만든 요리",
                "description_en": "Korean rice balls",
                "primary_ingredients": ["rice", "sesame oil", "salt"],
                "allergens": ["sesame"],
                "spice_level": 0,
                "difficulty_score": 1,
            },
            {
                "name_ko": "유부초밥",
                "name_en": "Yubu Chobap (Fried Tofu Sushi)",
                "concept": "밥류",
                "description_ko": "유부에 초밥을 넣은 요리",
                "description_en": "Sushi rice in fried tofu pouches",
                "primary_ingredients": ["rice", "fried tofu", "vinegar"],
                "allergens": ["soy"],
                "spice_level": 0,
                "difficulty_score": 1,
            },
            {
                "name_ko": "참치마요덮밥",
                "name_en": "Chamchi Mayo Deopbap (Tuna Mayo Rice Bowl)",
                "concept": "덮밥",
                "description_ko": "참치마요를 밥 위에 얹은 덮밥",
                "description_en": "Rice bowl with tuna and mayonnaise",
                "primary_ingredients": [
                    "rice",
                    "canned tuna",
                    "mayonnaise",
                    "vegetables",
                ],
                "allergens": ["fish", "egg"],
                "spice_level": 0,
                "difficulty_score": 1,
            },
        ]
    )

    # ========================================
    # 면류 추가 (Noodles) - 10개
    # ========================================

    menus.extend(
        [
            {
                "name_ko": "쫄면",
                "name_en": "Jjolmyeon (Chewy Spicy Noodles)",
                "concept": "국수",
                "description_ko": "쫄깃한 면에 매콤달콤한 양념을 비벼 먹는 요리",
                "description_en": "Chewy noodles in spicy-sweet sauce",
                "primary_ingredients": [
                    "chewy noodles",
                    "gochujang",
                    "vegetables",
                    "egg",
                ],
                "allergens": ["wheat", "egg", "soy"],
                "spice_level": 3,
                "difficulty_score": 1,
            },
            {
                "name_ko": "밀면",
                "name_en": "Milmyeon (Wheat Noodles)",
                "concept": "냉면",
                "description_ko": "부산 지역의 차가운 밀가루 면 요리",
                "description_en": "Cold wheat noodles, Busan specialty",
                "primary_ingredients": ["wheat noodles", "broth", "vegetables"],
                "allergens": ["wheat"],
                "spice_level": 1,
                "difficulty_score": 2,
            },
            {
                "name_ko": "쟁반국수",
                "name_en": "Jaengban Guksu (Platter Noodles)",
                "concept": "국수",
                "description_ko": "쟁반에 담아 먹는 비빔국수",
                "description_en": "Mixed noodles served on a platter",
                "primary_ingredients": ["wheat noodles", "gochujang", "vegetables"],
                "allergens": ["wheat", "soy"],
                "spice_level": 3,
                "difficulty_score": 1,
            },
            {
                "name_ko": "막국수",
                "name_en": "Makguksu (Buckwheat Noodles)",
                "concept": "냉면",
                "description_ko": "메밀면에 동치미 국물을 넣고 비벼 먹는 강원도 향토 음식",
                "description_en": "Buckwheat noodles with radish water kimchi, Gangwon-do specialty",
                "primary_ingredients": [
                    "buckwheat noodles",
                    "radish kimchi",
                    "vegetables",
                ],
                "allergens": ["buckwheat"],
                "spice_level": 1,
                "difficulty_score": 2,
            },
            {
                "name_ko": "온면",
                "name_en": "Onmyeon (Hot Wheat Noodles)",
                "concept": "국수",
                "description_ko": "따뜻한 육수에 말아 먹는 국수",
                "description_en": "Wheat noodles in hot broth",
                "primary_ingredients": ["wheat noodles", "broth", "vegetables"],
                "allergens": ["wheat"],
                "spice_level": 0,
                "difficulty_score": 1,
            },
            {
                "name_ko": "쫄국수",
                "name_en": "Jjolguksu (Chewy Noodle Soup)",
                "concept": "국수",
                "description_ko": "쫄깃한 면을 국물에 말아 먹는 요리",
                "description_en": "Chewy noodles in broth",
                "primary_ingredients": ["chewy noodles", "broth", "vegetables"],
                "allergens": ["wheat"],
                "spice_level": 0,
                "difficulty_score": 1,
            },
            {
                "name_ko": "우동",
                "name_en": "Udong (Udon Noodles)",
                "concept": "국수",
                "description_ko": "굵은 면을 국물에 말아 먹는 일본식 국수",
                "description_en": "Thick wheat noodles in broth, Japanese-style",
                "primary_ingredients": ["thick noodles", "broth", "tempura"],
                "allergens": ["wheat"],
                "spice_level": 0,
                "difficulty_score": 1,
            },
            {
                "name_ko": "짬뽕",
                "name_en": "Jjamppong (Spicy Seafood Noodle Soup)",
                "concept": "국수",
                "description_ko": "해물을 넣고 매콤하게 끓인 중국식 국수",
                "description_en": "Spicy seafood noodle soup, Chinese-Korean fusion",
                "primary_ingredients": [
                    "noodles",
                    "seafood",
                    "vegetables",
                    "gochugaru",
                ],
                "allergens": ["wheat", "seafood", "shellfish"],
                "spice_level": 4,
                "difficulty_score": 2,
            },
            {
                "name_ko": "짜장면",
                "name_en": "Jjajangmyeon (Black Bean Noodles)",
                "concept": "국수",
                "description_ko": "춘장을 넣고 볶은 소스를 면에 비벼 먹는 중국식 국수",
                "description_en": "Noodles with black bean sauce, Chinese-Korean fusion",
                "primary_ingredients": [
                    "noodles",
                    "black bean paste",
                    "pork",
                    "vegetables",
                ],
                "allergens": ["wheat", "pork", "soy"],
                "spice_level": 0,
                "difficulty_score": 1,
            },
            {
                "name_ko": "라볶이",
                "name_en": "Rabokki (Ramen Tteokbokki)",
                "concept": "라면",
                "description_ko": "라면과 떡볶이를 함께 끓인 요리",
                "description_en": "Ramen noodles with spicy rice cakes",
                "primary_ingredients": [
                    "ramen noodles",
                    "rice cakes",
                    "gochujang",
                    "fish cakes",
                ],
                "allergens": ["wheat", "fish", "soy"],
                "spice_level": 3,
                "difficulty_score": 1,
            },
        ]
    )

    # ========================================
    # 찜/조림 추가 (Braised & Steamed) - 10개
    # ========================================

    menus.extend(
        [
            {
                "name_ko": "안동찜닭",
                "name_en": "Andong Jjimdak (Braised Chicken)",
                "concept": "찜",
                "description_ko": "닭과 당면을 간장 양념으로 찜한 안동 향토 음식",
                "description_en": "Braised chicken with glass noodles in soy sauce, Andong specialty",
                "primary_ingredients": [
                    "chicken",
                    "glass noodles",
                    "potato",
                    "carrot",
                    "soy sauce",
                ],
                "allergens": ["chicken", "soy"],
                "spice_level": 1,
                "difficulty_score": 2,
            },
            {
                "name_ko": "닭볶음탕",
                "name_en": "Dakbokkeumtang (Spicy Braised Chicken)",
                "concept": "찜",
                "description_ko": "닭을 감자와 함께 매콤하게 조린 요리",
                "description_en": "Spicy braised chicken with potatoes",
                "primary_ingredients": ["chicken", "potato", "carrot", "gochugaru"],
                "allergens": ["chicken"],
                "spice_level": 3,
                "difficulty_score": 2,
            },
            {
                "name_ko": "꽁치조림",
                "name_en": "Kkongchi Jorim (Braised Saury)",
                "concept": "조림",
                "description_ko": "꽁치를 무와 함께 간장 양념으로 조린 요리",
                "description_en": "Saury braised with radish in soy sauce",
                "primary_ingredients": ["saury", "radish", "soy sauce"],
                "allergens": ["fish", "soy"],
                "spice_level": 1,
                "difficulty_score": 2,
            },
            {
                "name_ko": "감자조림",
                "name_en": "Gamja Jorim (Braised Potatoes)",
                "concept": "조림",
                "description_ko": "감자를 간장 양념으로 조린 반찬",
                "description_en": "Potatoes braised in soy sauce",
                "primary_ingredients": ["potato", "soy sauce", "sugar"],
                "allergens": ["soy"],
                "spice_level": 0,
                "difficulty_score": 1,
            },
            {
                "name_ko": "장조림",
                "name_en": "Jangjorim (Soy Braised Beef)",
                "concept": "조림",
                "description_ko": "소고기를 간장에 조린 반찬",
                "description_en": "Beef braised in soy sauce",
                "primary_ingredients": ["beef", "soy sauce", "quail eggs"],
                "allergens": ["beef", "soy", "egg"],
                "spice_level": 0,
                "difficulty_score": 2,
            },
            {
                "name_ko": "메추리알조림",
                "name_en": "Mechurial Jorim (Braised Quail Eggs)",
                "concept": "조림",
                "description_ko": "메추리알을 간장 양념으로 조린 반찬",
                "description_en": "Quail eggs braised in soy sauce",
                "primary_ingredients": ["quail eggs", "soy sauce", "sugar"],
                "allergens": ["egg", "soy"],
                "spice_level": 0,
                "difficulty_score": 1,
            },
            {
                "name_ko": "콩조림",
                "name_en": "Kong Jorim (Braised Black Beans)",
                "concept": "조림",
                "description_ko": "검은콩을 간장에 조린 반찬",
                "description_en": "Black beans braised in soy sauce",
                "primary_ingredients": ["black beans", "soy sauce"],
                "allergens": ["soy"],
                "spice_level": 0,
                "difficulty_score": 1,
            },
            {
                "name_ko": "멸치조림",
                "name_en": "Myeolchi Jorim (Braised Anchovies)",
                "concept": "조림",
                "description_ko": "멸치를 간장에 볶아 조린 반찬",
                "description_en": "Anchovies braised in soy sauce",
                "primary_ingredients": ["anchovies", "soy sauce", "gochugaru"],
                "allergens": ["fish", "soy"],
                "spice_level": 1,
                "difficulty_score": 1,
            },
            {
                "name_ko": "어묵조림",
                "name_en": "Eomuk Jorim (Braised Fish Cake)",
                "concept": "조림",
                "description_ko": "어묵을 간장 양념으로 조린 반찬",
                "description_en": "Fish cake braised in soy sauce",
                "primary_ingredients": ["fish cake", "soy sauce", "vegetables"],
                "allergens": ["fish", "soy"],
                "spice_level": 0,
                "difficulty_score": 1,
            },
            {
                "name_ko": "콩나물찜",
                "name_en": "Kongnamul Jjim (Steamed Bean Sprouts)",
                "concept": "찜",
                "description_ko": "콩나물을 쪄서 양념한 반찬",
                "description_en": "Steamed bean sprouts with seasoning",
                "primary_ingredients": ["bean sprouts", "garlic", "sesame oil"],
                "allergens": ["sesame"],
                "spice_level": 1,
                "difficulty_score": 1,
            },
        ]
    )

    # ========================================
    # 한정식/코스 (Korean Table d'hote) - 10개
    # ========================================

    menus.extend(
        [
            {
                "name_ko": "백반",
                "name_en": "Baekban (Korean Home-style Meal)",
                "concept": "정식/백반",
                "description_ko": "밥과 국, 반찬이 함께 나오는 가정식 정식",
                "description_en": "Home-style Korean meal with rice, soup, and side dishes",
                "primary_ingredients": ["rice", "soup", "side dishes"],
                "allergens": [],
                "spice_level": 0,
                "difficulty_score": 1,
            },
            {
                "name_ko": "불고기정식",
                "name_en": "Bulgogi Jeongsik (Bulgogi Set Menu)",
                "concept": "정식/백반",
                "description_ko": "불고기와 밥, 반찬이 함께 나오는 정식",
                "description_en": "Set menu with bulgogi, rice, and side dishes",
                "primary_ingredients": ["bulgogi", "rice", "side dishes"],
                "allergens": ["beef", "soy"],
                "spice_level": 0,
                "difficulty_score": 2,
            },
            {
                "name_ko": "갈비정식",
                "name_en": "Galbi Jeongsik (Galbi Set Menu)",
                "concept": "정식/백반",
                "description_ko": "갈비와 밥, 반찬이 함께 나오는 정식",
                "description_en": "Set menu with galbi, rice, and side dishes",
                "primary_ingredients": ["galbi", "rice", "side dishes"],
                "allergens": ["beef", "soy"],
                "spice_level": 0,
                "difficulty_score": 2,
            },
            {
                "name_ko": "생선구이정식",
                "name_en": "Saengseon Gui Jeongsik (Grilled Fish Set Menu)",
                "concept": "정식/백반",
                "description_ko": "생선구이와 밥, 반찬이 함께 나오는 정식",
                "description_en": "Set menu with grilled fish, rice, and side dishes",
                "primary_ingredients": ["grilled fish", "rice", "side dishes"],
                "allergens": ["fish"],
                "spice_level": 0,
                "difficulty_score": 2,
            },
            {
                "name_ko": "제육정식",
                "name_en": "Jeyuk Jeongsik (Spicy Pork Set Menu)",
                "concept": "정식/백반",
                "description_ko": "제육볶음과 밥, 반찬이 함께 나오는 정식",
                "description_en": "Set menu with spicy stir-fried pork, rice, and side dishes",
                "primary_ingredients": ["spicy pork", "rice", "side dishes"],
                "allergens": ["pork", "soy"],
                "spice_level": 3,
                "difficulty_score": 2,
            },
            {
                "name_ko": "정갈비정식",
                "name_en": "Jeonggalbi Jeongsik (Premium Galbi Set Menu)",
                "concept": "정식/백반",
                "description_ko": "정갈비와 밥, 반찬이 함께 나오는 고급 정식",
                "description_en": "Premium set menu with galbi, rice, and side dishes",
                "primary_ingredients": ["premium galbi", "rice", "side dishes"],
                "allergens": ["beef", "soy"],
                "spice_level": 0,
                "difficulty_score": 2,
            },
            {
                "name_ko": "삼겹살정식",
                "name_en": "Samgyeopsal Jeongsik (Pork Belly Set Menu)",
                "concept": "정식/백반",
                "description_ko": "삼겹살과 밥, 반찬이 함께 나오는 정식",
                "description_en": "Set menu with pork belly, rice, and side dishes",
                "primary_ingredients": ["pork belly", "rice", "side dishes"],
                "allergens": ["pork"],
                "spice_level": 0,
                "difficulty_score": 2,
            },
            {
                "name_ko": "두부정식",
                "name_en": "Dubu Jeongsik (Tofu Set Menu)",
                "concept": "정식/백반",
                "description_ko": "두부 요리와 밥, 반찬이 함께 나오는 정식",
                "description_en": "Set menu with tofu dishes, rice, and side dishes",
                "primary_ingredients": ["tofu", "rice", "side dishes"],
                "allergens": ["soy"],
                "spice_level": 0,
                "difficulty_score": 1,
            },
            {
                "name_ko": "비빔밥정식",
                "name_en": "Bibimbap Jeongsik (Bibimbap Set Menu)",
                "concept": "정식/백반",
                "description_ko": "비빔밥과 반찬이 함께 나오는 정식",
                "description_en": "Set menu with bibimbap and side dishes",
                "primary_ingredients": ["bibimbap", "side dishes"],
                "allergens": ["egg", "soy"],
                "spice_level": 1,
                "difficulty_score": 2,
            },
            {
                "name_ko": "한정식특선",
                "name_en": "Hanjeongsik Teukseeon (Premium Korean Table d'hote)",
                "concept": "정식/백반",
                "description_ko": "특선 요리와 다양한 반찬이 함께 나오는 고급 한정식",
                "description_en": "Premium full-course Korean meal with special dishes",
                "primary_ingredients": [
                    "rice",
                    "soup",
                    "premium dishes",
                    "many side dishes",
                ],
                "allergens": [],
                "spice_level": 1,
                "difficulty_score": 3,
            },
        ]
    )

    # ========================================
    # 분식 추가 (Snacks) - 15개
    # ========================================

    menus.extend(
        [
            {
                "name_ko": "떡꼬치",
                "name_en": "Tteok Kkochi (Rice Cake Skewers)",
                "concept": "떡볶이",
                "description_ko": "떡을 꼬치에 꽂아 양념을 발라 먹는 분식",
                "description_en": "Rice cake skewers with sweet spicy sauce",
                "primary_ingredients": ["rice cakes", "gochujang", "skewers"],
                "allergens": ["soy"],
                "spice_level": 2,
                "difficulty_score": 1,
            },
            {
                "name_ko": "핫도그",
                "name_en": "Hot Dog (Korean-style)",
                "concept": "튀김",
                "description_ko": "소시지에 튀김옷을 입혀 튀긴 분식",
                "description_en": "Battered and fried hot dog on a stick",
                "primary_ingredients": ["sausage", "flour", "breadcrumbs"],
                "allergens": ["wheat", "pork"],
                "spice_level": 0,
                "difficulty_score": 1,
            },
            {
                "name_ko": "붕어빵",
                "name_en": "Bungeoppang (Fish-shaped Pastry)",
                "concept": "부침개",
                "description_ko": "붕어 모양의 틀에 팥을 넣고 구운 겨울 간식",
                "description_en": "Fish-shaped pastry filled with red bean paste, winter snack",
                "primary_ingredients": ["flour", "red bean paste"],
                "allergens": ["wheat"],
                "spice_level": 0,
                "difficulty_score": 1,
            },
            {
                "name_ko": "쫄볶이",
                "name_en": "Jjolbokki (Chewy Spicy Rice Cakes)",
                "concept": "떡볶이",
                "description_ko": "쫄면과 떡을 함께 매콤하게 볶은 분식",
                "description_en": "Spicy stir-fried rice cakes with chewy noodles",
                "primary_ingredients": ["rice cakes", "chewy noodles", "gochujang"],
                "allergens": ["wheat", "soy"],
                "spice_level": 3,
                "difficulty_score": 1,
            },
            {
                "name_ko": "김말이튀김",
                "name_en": "Gimmari Twigim (Fried Seaweed Rolls)",
                "concept": "튀김",
                "description_ko": "김에 당면을 말아 튀긴 분식",
                "description_en": "Deep-fried seaweed rolls with glass noodles",
                "primary_ingredients": ["seaweed", "glass noodles", "flour"],
                "allergens": ["wheat"],
                "spice_level": 0,
                "difficulty_score": 1,
            },
            {
                "name_ko": "튀김",
                "name_en": "Twigim (Assorted Fritters)",
                "concept": "튀김",
                "description_ko": "각종 재료에 튀김옷을 입혀 튀긴 분식",
                "description_en": "Assorted battered and deep-fried items",
                "primary_ingredients": ["vegetables", "flour", "batter"],
                "allergens": ["wheat"],
                "spice_level": 0,
                "difficulty_score": 1,
            },
            {
                "name_ko": "야채튀김",
                "name_en": "Yachae Twigim (Vegetable Fritters)",
                "concept": "튀김",
                "description_ko": "야채에 튀김옷을 입혀 튀긴 요리",
                "description_en": "Battered and deep-fried vegetables",
                "primary_ingredients": ["vegetables", "flour", "batter"],
                "allergens": ["wheat"],
                "spice_level": 0,
                "difficulty_score": 1,
            },
            {
                "name_ko": "고구마튀김",
                "name_en": "Goguma Twigim (Sweet Potato Fritters)",
                "concept": "튀김",
                "description_ko": "고구마를 튀긴 분식",
                "description_en": "Battered and deep-fried sweet potato",
                "primary_ingredients": ["sweet potato", "flour"],
                "allergens": ["wheat"],
                "spice_level": 0,
                "difficulty_score": 1,
            },
            {
                "name_ko": "순대튀김",
                "name_en": "Sundae Twigim (Fried Blood Sausage)",
                "concept": "튀김",
                "description_ko": "순대를 튀긴 분식",
                "description_en": "Deep-fried Korean blood sausage",
                "primary_ingredients": ["blood sausage", "flour"],
                "allergens": ["pork", "wheat"],
                "spice_level": 0,
                "difficulty_score": 2,
            },
            {
                "name_ko": "어묵",
                "name_en": "Eomuk (Fish Cake)",
                "concept": "튀김",
                "description_ko": "어묵을 국물에 넣어 먹는 분식",
                "description_en": "Fish cake in broth",
                "primary_ingredients": ["fish cake", "broth"],
                "allergens": ["fish"],
                "spice_level": 0,
                "difficulty_score": 1,
            },
            {
                "name_ko": "꼬치어묵",
                "name_en": "Kkochi Eomuk (Fish Cake Skewers)",
                "concept": "튀김",
                "description_ko": "어묵을 꼬치에 꽂아 먹는 분식",
                "description_en": "Fish cake on skewers in broth",
                "primary_ingredients": ["fish cake", "skewers", "broth"],
                "allergens": ["fish"],
                "spice_level": 0,
                "difficulty_score": 1,
            },
            {
                "name_ko": "김치만두",
                "name_en": "Kimchi Mandu (Kimchi Dumplings)",
                "concept": "튀김",
                "description_ko": "김치를 넣은 만두",
                "description_en": "Dumplings filled with kimchi",
                "primary_ingredients": ["dumpling wrapper", "kimchi", "pork", "tofu"],
                "allergens": ["wheat", "pork", "soy"],
                "spice_level": 1,
                "difficulty_score": 2,
            },
            {
                "name_ko": "군만두",
                "name_en": "Gun Mandu (Pan-fried Dumplings)",
                "concept": "튀김",
                "description_ko": "만두를 팬에 구워 만든 요리",
                "description_en": "Pan-fried dumplings",
                "primary_ingredients": ["dumpling wrapper", "pork", "vegetables"],
                "allergens": ["wheat", "pork"],
                "spice_level": 0,
                "difficulty_score": 1,
            },
            {
                "name_ko": "찐만두",
                "name_en": "Jjin Mandu (Steamed Dumplings)",
                "concept": "튀김",
                "description_ko": "만두를 쪄서 먹는 요리",
                "description_en": "Steamed dumplings",
                "primary_ingredients": ["dumpling wrapper", "pork", "vegetables"],
                "allergens": ["wheat", "pork"],
                "spice_level": 0,
                "difficulty_score": 1,
            },
            {
                "name_ko": "왕만두",
                "name_en": "Wang Mandu (King-size Dumplings)",
                "concept": "튀김",
                "description_ko": "큰 사이즈의 만두",
                "description_en": "King-size dumplings",
                "primary_ingredients": [
                    "dumpling wrapper",
                    "pork",
                    "vegetables",
                    "glass noodles",
                ],
                "allergens": ["wheat", "pork"],
                "spice_level": 0,
                "difficulty_score": 2,
            },
        ]
    )

    # ========================================
    # 전/부침 추가 (Pancakes) - 8개
    # ========================================

    menus.extend(
        [
            {
                "name_ko": "감자전",
                "name_en": "Gamja Jeon (Potato Pancake)",
                "concept": "전",
                "description_ko": "감자를 갈아 부친 전",
                "description_en": "Savory pancake made with grated potato",
                "primary_ingredients": ["potato", "flour", "onion"],
                "allergens": ["wheat"],
                "spice_level": 0,
                "difficulty_score": 1,
            },
            {
                "name_ko": "녹두전",
                "name_en": "Nokdu Jeon (Mung Bean Pancake)",
                "concept": "전",
                "description_ko": "녹두를 갈아 부친 전",
                "description_en": "Savory pancake made with ground mung beans",
                "primary_ingredients": ["mung beans", "pork", "vegetables"],
                "allergens": ["pork"],
                "spice_level": 0,
                "difficulty_score": 2,
            },
            {
                "name_ko": "떡갈비",
                "name_en": "Tteokgalbi (Grilled Short Rib Patties)",
                "concept": "전",
                "description_ko": "다진 갈비를 떡 모양으로 빚어 구운 요리",
                "description_en": "Grilled minced short rib patties",
                "primary_ingredients": ["beef ribs", "pork", "onion"],
                "allergens": ["beef", "pork"],
                "spice_level": 0,
                "difficulty_score": 2,
            },
            {
                "name_ko": "굴전",
                "name_en": "Gul Jeon (Oyster Pancake)",
                "concept": "전",
                "description_ko": "굴을 넣고 부친 전",
                "description_en": "Savory pancake with oysters",
                "primary_ingredients": ["oysters", "flour", "egg"],
                "allergens": ["shellfish", "wheat", "egg"],
                "spice_level": 0,
                "difficulty_score": 2,
            },
            {
                "name_ko": "애호박전",
                "name_en": "Aehobak Jeon (Zucchini Pancake)",
                "concept": "전",
                "description_ko": "애호박을 썰어 부친 전",
                "description_en": "Savory pancake with sliced zucchini",
                "primary_ingredients": ["zucchini", "flour", "egg"],
                "allergens": ["wheat", "egg"],
                "spice_level": 0,
                "difficulty_score": 1,
            },
            {
                "name_ko": "부추전",
                "name_en": "Buchu Jeon (Chive Pancake)",
                "concept": "전",
                "description_ko": "부추를 넣고 부친 전",
                "description_en": "Savory pancake with chives",
                "primary_ingredients": ["chives", "flour", "egg"],
                "allergens": ["wheat", "egg"],
                "spice_level": 0,
                "difficulty_score": 1,
            },
            {
                "name_ko": "고추전",
                "name_en": "Gochu Jeon (Pepper Pancake)",
                "concept": "전",
                "description_ko": "고추에 고기를 넣고 부친 전",
                "description_en": "Savory pancake with stuffed peppers",
                "primary_ingredients": ["peppers", "beef", "flour", "egg"],
                "allergens": ["beef", "wheat", "egg"],
                "spice_level": 1,
                "difficulty_score": 2,
            },
            {
                "name_ko": "생선전",
                "name_en": "Saengseon Jeon (Pan-fried Fish)",
                "concept": "전",
                "description_ko": "생선에 계란옷을 입혀 부친 전",
                "description_en": "Fish slices coated with egg and pan-fried",
                "primary_ingredients": ["fish", "egg", "flour"],
                "allergens": ["fish", "egg", "wheat"],
                "spice_level": 0,
                "difficulty_score": 2,
            },
        ]
    )

    # ========================================
    # 반찬/나물 (Side Dishes) - 10개
    # ========================================

    menus.extend(
        [
            {
                "name_ko": "시금치나물",
                "name_en": "Sigeumchi Namul (Seasoned Spinach)",
                "concept": "나물",
                "description_ko": "시금치를 데쳐 양념한 반찬",
                "description_en": "Blanched spinach with sesame oil",
                "primary_ingredients": ["spinach", "sesame oil", "garlic"],
                "allergens": ["sesame"],
                "spice_level": 0,
                "difficulty_score": 1,
            },
            {
                "name_ko": "콩나물무침",
                "name_en": "Kongnamul Muchim (Seasoned Bean Sprouts)",
                "concept": "나물",
                "description_ko": "콩나물을 데쳐 양념한 반찬",
                "description_en": "Blanched bean sprouts with sesame oil",
                "primary_ingredients": ["bean sprouts", "sesame oil", "garlic"],
                "allergens": ["sesame"],
                "spice_level": 0,
                "difficulty_score": 1,
            },
            {
                "name_ko": "멸치볶음",
                "name_en": "Myeolchi Bokkeum (Stir-fried Anchovies)",
                "concept": "조림",
                "description_ko": "멸치를 볶아 만든 반찬",
                "description_en": "Stir-fried dried anchovies with soy sauce",
                "primary_ingredients": ["dried anchovies", "soy sauce", "sugar"],
                "allergens": ["fish", "soy"],
                "spice_level": 0,
                "difficulty_score": 1,
            },
            {
                "name_ko": "총각김치",
                "name_en": "Chonggak Kimchi (Ponytail Radish Kimchi)",
                "concept": "김치",
                "description_ko": "총각무를 김치로 담근 반찬",
                "description_en": "Fermented ponytail radish kimchi",
                "primary_ingredients": ["ponytail radish", "gochugaru", "fish sauce"],
                "allergens": ["fish"],
                "spice_level": 2,
                "difficulty_score": 2,
            },
            {
                "name_ko": "깍두기",
                "name_en": "Kkakdugi (Radish Kimchi)",
                "concept": "김치",
                "description_ko": "무를 깍둑썰기하여 담근 김치",
                "description_en": "Cubed radish kimchi",
                "primary_ingredients": ["radish", "gochugaru", "fish sauce"],
                "allergens": ["fish"],
                "spice_level": 2,
                "difficulty_score": 2,
            },
            {
                "name_ko": "오이김치",
                "name_en": "Oi Kimchi (Cucumber Kimchi)",
                "concept": "김치",
                "description_ko": "오이를 김치로 담근 반찬",
                "description_en": "Fermented cucumber kimchi",
                "primary_ingredients": ["cucumber", "gochugaru", "fish sauce"],
                "allergens": ["fish"],
                "spice_level": 2,
                "difficulty_score": 2,
            },
            {
                "name_ko": "무생채",
                "name_en": "Musaengchae (Spicy Radish Salad)",
                "concept": "나물",
                "description_ko": "무를 채 썰어 양념한 반찬",
                "description_en": "Julienned radish in spicy dressing",
                "primary_ingredients": ["radish", "gochugaru", "vinegar"],
                "allergens": [],
                "spice_level": 2,
                "difficulty_score": 1,
            },
            {
                "name_ko": "오이무침",
                "name_en": "Oi Muchim (Seasoned Cucumber)",
                "concept": "나물",
                "description_ko": "오이를 양념에 무친 반찬",
                "description_en": "Cucumber in spicy dressing",
                "primary_ingredients": ["cucumber", "gochugaru", "sesame oil"],
                "allergens": ["sesame"],
                "spice_level": 1,
                "difficulty_score": 1,
            },
            {
                "name_ko": "도라지무침",
                "name_en": "Doraji Muchim (Seasoned Bellflower Root)",
                "concept": "나물",
                "description_ko": "도라지를 양념에 무친 반찬",
                "description_en": "Seasoned bellflower root",
                "primary_ingredients": ["bellflower root", "gochugaru", "sesame oil"],
                "allergens": ["sesame"],
                "spice_level": 1,
                "difficulty_score": 2,
            },
            {
                "name_ko": "고사리나물",
                "name_en": "Gosari Namul (Seasoned Fernbrake)",
                "concept": "나물",
                "description_ko": "고사리를 볶아 양념한 반찬",
                "description_en": "Stir-fried fernbrake with sesame oil",
                "primary_ingredients": ["fernbrake", "soy sauce", "sesame oil"],
                "allergens": ["soy", "sesame"],
                "spice_level": 0,
                "difficulty_score": 2,
            },
        ]
    )

    # ========================================
    # 디저트/음료 (Desserts & Drinks) - 10개
    # ========================================

    menus.extend(
        [
            {
                "name_ko": "수정과",
                "name_en": "Sujeonggwa (Cinnamon Punch)",
                "concept": "음료",
                "description_ko": "계피와 생강을 넣고 달게 만든 전통 음료",
                "description_en": "Sweet cinnamon punch with dried persimmons",
                "primary_ingredients": [
                    "cinnamon",
                    "ginger",
                    "sugar",
                    "dried persimmon",
                ],
                "allergens": [],
                "spice_level": 0,
                "difficulty_score": 2,
            },
            {
                "name_ko": "식혜",
                "name_en": "Sikhye (Sweet Rice Drink)",
                "concept": "음료",
                "description_ko": "엿기름으로 발효시킨 달콤한 음료",
                "description_en": "Sweet fermented rice drink",
                "primary_ingredients": ["rice", "malt", "sugar"],
                "allergens": [],
                "spice_level": 0,
                "difficulty_score": 2,
            },
            {
                "name_ko": "매실차",
                "name_en": "Maesil Cha (Plum Tea)",
                "concept": "음료",
                "description_ko": "매실청을 물에 타서 마시는 차",
                "description_en": "Sweet plum tea",
                "primary_ingredients": ["plum syrup", "water"],
                "allergens": [],
                "spice_level": 0,
                "difficulty_score": 1,
            },
            {
                "name_ko": "팥빙수",
                "name_en": "Patbingsu (Shaved Ice with Red Beans)",
                "concept": "디저트",
                "description_ko": "얼음을 갈아 팥과 과일을 얹은 여름 디저트",
                "description_en": "Shaved ice with sweet red beans and toppings",
                "primary_ingredients": ["shaved ice", "red beans", "milk", "fruits"],
                "allergens": ["dairy"],
                "spice_level": 0,
                "difficulty_score": 1,
            },
            {
                "name_ko": "인절미",
                "name_en": "Injeolmi (Soybean Powder Rice Cake)",
                "concept": "떡/한과",
                "description_ko": "찐 찹쌀떡에 콩가루를 묻힌 떡",
                "description_en": "Glutinous rice cake coated with soybean powder",
                "primary_ingredients": ["glutinous rice", "soybean powder"],
                "allergens": ["soy"],
                "spice_level": 0,
                "difficulty_score": 2,
            },
            {
                "name_ko": "약과",
                "name_en": "Yakgwa (Honey Cookies)",
                "concept": "떡/한과",
                "description_ko": "밀가루 반죽을 기름에 튀겨 꿀에 담근 한과",
                "description_en": "Fried wheat cookies soaked in honey syrup",
                "primary_ingredients": ["flour", "honey", "oil"],
                "allergens": ["wheat"],
                "spice_level": 0,
                "difficulty_score": 2,
            },
            {
                "name_ko": "한과",
                "name_en": "Hangwa (Traditional Korean Sweets)",
                "concept": "떡/한과",
                "description_ko": "전통 방식으로 만든 한국 과자",
                "description_en": "Traditional Korean confections",
                "primary_ingredients": ["rice flour", "honey", "nuts"],
                "allergens": ["tree nuts"],
                "spice_level": 0,
                "difficulty_score": 3,
            },
            {
                "name_ko": "경단",
                "name_en": "Gyeongdan (Filled Rice Balls)",
                "concept": "떡/한과",
                "description_ko": "찹쌀가루로 만든 떡에 고물을 묻힌 한과",
                "description_en": "Glutinous rice balls coated with bean powder",
                "primary_ingredients": ["glutinous rice flour", "bean powder"],
                "allergens": ["soy"],
                "spice_level": 0,
                "difficulty_score": 2,
            },
            {
                "name_ko": "송편",
                "name_en": "Songpyeon (Half-moon Rice Cake)",
                "concept": "떡/한과",
                "description_ko": "반달 모양의 떡 안에 고물을 넣은 추석 음식",
                "description_en": "Half-moon rice cake with sweet filling, Chuseok food",
                "primary_ingredients": ["rice flour", "sesame", "honey"],
                "allergens": ["sesame"],
                "spice_level": 0,
                "difficulty_score": 3,
            },
            {
                "name_ko": "모찌",
                "name_en": "Mochi (Japanese Rice Cake)",
                "concept": "떡/한과",
                "description_ko": "일본식 찹쌀떡",
                "description_en": "Japanese glutinous rice cake",
                "primary_ingredients": ["glutinous rice", "sugar"],
                "allergens": [],
                "spice_level": 0,
                "difficulty_score": 2,
            },
        ]
    )

    # ========================================
    # 주류/안주 추가 (Drinking Snacks) - 10개
    # ========================================

    menus.extend(
        [
            {
                "name_ko": "양념치킨",
                "name_en": "Yangnyeom Chicken (Spicy Fried Chicken)",
                "concept": "육류안주",
                "description_ko": "튀긴 닭에 매콤달콤한 양념을 버무린 치킨",
                "description_en": "Fried chicken with spicy-sweet sauce",
                "primary_ingredients": ["chicken", "gochujang", "sugar"],
                "allergens": ["chicken", "wheat", "soy"],
                "spice_level": 2,
                "difficulty_score": 2,
            },
            {
                "name_ko": "간장치킨",
                "name_en": "Ganjang Chicken (Soy Sauce Fried Chicken)",
                "concept": "육류안주",
                "description_ko": "튀긴 닭에 간장 양념을 버무린 치킨",
                "description_en": "Fried chicken with soy sauce glaze",
                "primary_ingredients": ["chicken", "soy sauce", "sugar"],
                "allergens": ["chicken", "wheat", "soy"],
                "spice_level": 0,
                "difficulty_score": 2,
            },
            {
                "name_ko": "후라이드치킨",
                "name_en": "Fried Chicken",
                "concept": "육류안주",
                "description_ko": "튀긴 치킨",
                "description_en": "Plain fried chicken",
                "primary_ingredients": ["chicken", "flour"],
                "allergens": ["chicken", "wheat"],
                "spice_level": 0,
                "difficulty_score": 2,
            },
            {
                "name_ko": "골뱅이무침",
                "name_en": "Golbaengi Muchim (Spicy Sea Snails)",
                "concept": "해물안주",
                "description_ko": "골뱅이를 매콤하게 무친 안주",
                "description_en": "Spicy sea snails with vegetables",
                "primary_ingredients": ["sea snails", "gochujang", "vegetables"],
                "allergens": ["shellfish", "soy"],
                "spice_level": 3,
                "difficulty_score": 2,
            },
            {
                "name_ko": "오돌뼈",
                "name_en": "Odolppyeo (Crunchy Chicken Cartilage)",
                "concept": "육류안주",
                "description_ko": "닭 연골을 양념해 구운 안주",
                "description_en": "Grilled chicken cartilage",
                "primary_ingredients": ["chicken cartilage", "gochujang"],
                "allergens": ["chicken", "soy"],
                "spice_level": 2,
                "difficulty_score": 2,
            },
            {
                "name_ko": "쭈꾸미",
                "name_en": "Jjukkumi (Webfoot Octopus)",
                "concept": "해물안주",
                "description_ko": "쭈꾸미를 매콤하게 볶은 안주",
                "description_en": "Spicy stir-fried webfoot octopus",
                "primary_ingredients": ["webfoot octopus", "gochujang"],
                "allergens": ["seafood", "soy"],
                "spice_level": 4,
                "difficulty_score": 3,
            },
            {
                "name_ko": "닭똥집",
                "name_en": "Dakddongjip (Chicken Gizzards)",
                "concept": "육류안주",
                "description_ko": "닭의 모래주머니를 양념해 구운 안주",
                "description_en": "Grilled chicken gizzards",
                "primary_ingredients": ["chicken gizzards", "gochujang"],
                "allergens": ["chicken", "soy"],
                "spice_level": 2,
                "difficulty_score": 2,
            },
            {
                "name_ko": "낙지연포탕",
                "name_en": "Nakji Yeonpotang (Spicy Octopus Stew)",
                "concept": "해물안주",
                "description_ko": "낙지를 매콤하게 끓인 국물 요리",
                "description_en": "Spicy octopus stew",
                "primary_ingredients": ["octopus", "gochugaru", "vegetables"],
                "allergens": ["seafood"],
                "spice_level": 4,
                "difficulty_score": 3,
            },
            {
                "name_ko": "쥐포",
                "name_en": "Jwipo (Dried Squid)",
                "concept": "해물안주",
                "description_ko": "오징어를 말린 안주",
                "description_en": "Dried shredded squid",
                "primary_ingredients": ["dried squid"],
                "allergens": ["seafood"],
                "spice_level": 0,
                "difficulty_score": 1,
            },
            {
                "name_ko": "마른안주",
                "name_en": "Mareun Anju (Dried Snacks)",
                "concept": "육류안주",
                "description_ko": "말린 육포나 견과류 등의 안주",
                "description_en": "Assorted dried snacks (jerky, nuts, etc.)",
                "primary_ingredients": ["dried meat", "nuts"],
                "allergens": ["tree nuts", "peanuts"],
                "spice_level": 0,
                "difficulty_score": 1,
            },
        ]
    )

    # ========================================
    # 카페 메뉴 (Cafe Menu) - 14개
    # ========================================

    menus.extend(
        [
            {
                "name_ko": "아메리카노",
                "name_en": "Americano",
                "concept": "음료",
                "description_ko": "에스프레소에 물을 넣은 커피",
                "description_en": "Espresso with water",
                "primary_ingredients": ["espresso", "water"],
                "allergens": [],
                "spice_level": 0,
                "difficulty_score": 1,
            },
            {
                "name_ko": "카페라떼",
                "name_en": "Cafe Latte",
                "concept": "음료",
                "description_ko": "에스프레소에 우유를 넣은 커피",
                "description_en": "Espresso with steamed milk",
                "primary_ingredients": ["espresso", "milk"],
                "allergens": ["dairy"],
                "spice_level": 0,
                "difficulty_score": 1,
            },
            {
                "name_ko": "카푸치노",
                "name_en": "Cappuccino",
                "concept": "음료",
                "description_ko": "에스프레소와 거품 우유를 넣은 커피",
                "description_en": "Espresso with foamed milk",
                "primary_ingredients": ["espresso", "milk", "foam"],
                "allergens": ["dairy"],
                "spice_level": 0,
                "difficulty_score": 1,
            },
            {
                "name_ko": "카라멜마키아또",
                "name_en": "Caramel Macchiato",
                "concept": "음료",
                "description_ko": "에스프레소에 우유와 카라멜을 넣은 커피",
                "description_en": "Espresso with milk and caramel syrup",
                "primary_ingredients": ["espresso", "milk", "caramel"],
                "allergens": ["dairy"],
                "spice_level": 0,
                "difficulty_score": 1,
            },
            {
                "name_ko": "바닐라라떼",
                "name_en": "Vanilla Latte",
                "concept": "음료",
                "description_ko": "에스프레소에 우유와 바닐라 시럽을 넣은 커피",
                "description_en": "Espresso with milk and vanilla syrup",
                "primary_ingredients": ["espresso", "milk", "vanilla"],
                "allergens": ["dairy"],
                "spice_level": 0,
                "difficulty_score": 1,
            },
            {
                "name_ko": "핫초코",
                "name_en": "Hot Chocolate",
                "concept": "음료",
                "description_ko": "따뜻한 초콜릿 음료",
                "description_en": "Hot chocolate drink",
                "primary_ingredients": ["chocolate", "milk"],
                "allergens": ["dairy"],
                "spice_level": 0,
                "difficulty_score": 1,
            },
            {
                "name_ko": "녹차라떼",
                "name_en": "Green Tea Latte",
                "concept": "음료",
                "description_ko": "녹차와 우유를 섞은 라떼",
                "description_en": "Green tea with steamed milk",
                "primary_ingredients": ["green tea", "milk"],
                "allergens": ["dairy"],
                "spice_level": 0,
                "difficulty_score": 1,
            },
            {
                "name_ko": "생과일주스",
                "name_en": "Fresh Fruit Juice",
                "concept": "음료",
                "description_ko": "신선한 과일로 만든 주스",
                "description_en": "Fresh fruit juice",
                "primary_ingredients": ["fresh fruits"],
                "allergens": [],
                "spice_level": 0,
                "difficulty_score": 1,
            },
            {
                "name_ko": "딸기스무디",
                "name_en": "Strawberry Smoothie",
                "concept": "음료",
                "description_ko": "딸기와 얼음을 갈아 만든 음료",
                "description_en": "Blended strawberry and ice drink",
                "primary_ingredients": ["strawberry", "ice", "milk"],
                "allergens": ["dairy"],
                "spice_level": 0,
                "difficulty_score": 1,
            },
            {
                "name_ko": "망고스무디",
                "name_en": "Mango Smoothie",
                "concept": "음료",
                "description_ko": "망고와 얼음을 갈아 만든 음료",
                "description_en": "Blended mango and ice drink",
                "primary_ingredients": ["mango", "ice", "milk"],
                "allergens": ["dairy"],
                "spice_level": 0,
                "difficulty_score": 1,
            },
            {
                "name_ko": "크로플",
                "name_en": "Croffle (Croissant Waffle)",
                "concept": "디저트",
                "description_ko": "크루아상 반죽을 와플로 구운 디저트",
                "description_en": "Croissant dough cooked in waffle iron",
                "primary_ingredients": ["croissant dough", "butter"],
                "allergens": ["wheat", "dairy", "egg"],
                "spice_level": 0,
                "difficulty_score": 2,
            },
            {
                "name_ko": "소금빵",
                "name_en": "Sogeumbang (Salted Bread)",
                "concept": "디저트",
                "description_ko": "버터와 소금을 넣어 만든 빵",
                "description_en": "Buttery bread with sea salt",
                "primary_ingredients": ["flour", "butter", "salt"],
                "allergens": ["wheat", "dairy"],
                "spice_level": 0,
                "difficulty_score": 1,
            },
            {
                "name_ko": "마카롱",
                "name_en": "Macaron",
                "concept": "디저트",
                "description_ko": "프랑스식 머랭 쿠키",
                "description_en": "French meringue cookies",
                "primary_ingredients": ["almond flour", "egg white", "sugar"],
                "allergens": ["tree nuts", "egg"],
                "spice_level": 0,
                "difficulty_score": 3,
            },
            {
                "name_ko": "티라미수",
                "name_en": "Tiramisu",
                "concept": "디저트",
                "description_ko": "이탈리아식 커피 케이크",
                "description_en": "Italian coffee-flavored dessert",
                "primary_ingredients": ["mascarpone", "coffee", "egg", "cocoa"],
                "allergens": ["dairy", "egg", "wheat"],
                "spice_level": 0,
                "difficulty_score": 2,
            },
        ]
    )

    return menus
